'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace ConsultaPostpagoWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ConsultasPostpagoWSPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows")>  _
    Public Class ConsultasPostpagoWSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv28.tim.com.pe:8909/ConsultasPostpagoWS/ConsultasPostpagoSB11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaspostpagows/consultarDatosCliente", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function consultarDatosCliente(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> ByVal datosClienteRequest As datosClienteRequest) As <System.Xml.Serialization.XmlElementAttribute("datosClienteResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> datosClienteResponse
            Dim results() As Object = Me.Invoke("consultarDatosCliente", New Object() {datosClienteRequest})
            Return CType(results(0),datosClienteResponse)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarDatosCliente(ByVal datosClienteRequest As datosClienteRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarDatosCliente", New Object() {datosClienteRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarDatosCliente(ByVal asyncResult As System.IAsyncResult) As datosClienteResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),datosClienteResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaspostpagows/consultarDatosContrato", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function consultarDatosContrato(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> ByVal datosContratoRequest As datosContratoRequest) As <System.Xml.Serialization.XmlElementAttribute("datosContratoResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> datosContratoResponse
            Dim results() As Object = Me.Invoke("consultarDatosContrato", New Object() {datosContratoRequest})
            Return CType(results(0),datosContratoResponse)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarDatosContrato(ByVal datosContratoRequest As datosContratoRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarDatosContrato", New Object() {datosContratoRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarDatosContrato(ByVal asyncResult As System.IAsyncResult) As datosContratoResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),datosContratoResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaspostpagows/consultarServiciosLinea", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function consultarServiciosLinea(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> ByVal serviciosLineaRequest As serviciosLineaRequest) As <System.Xml.Serialization.XmlElementAttribute("serviciosLineaResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> serviciosLineaResponse
            Dim results() As Object = Me.Invoke("consultarServiciosLinea", New Object() {serviciosLineaRequest})
            Return CType(results(0),serviciosLineaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarServiciosLinea(ByVal serviciosLineaRequest As serviciosLineaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarServiciosLinea", New Object() {serviciosLineaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarServiciosLinea(ByVal asyncResult As System.IAsyncResult) As serviciosLineaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),serviciosLineaResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaspostpagows/leerCuentasMadre", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function leerCuentasMadre(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> ByVal leerCuentasMadreRequest As leerCuentasMadreRequest) As <System.Xml.Serialization.XmlElementAttribute("leerCuentasMadreResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> leerCuentasMadreResponse
            Dim results() As Object = Me.Invoke("leerCuentasMadre", New Object() {leerCuentasMadreRequest})
            Return CType(results(0),leerCuentasMadreResponse)
        End Function
        
        '<remarks/>
        Public Function BeginleerCuentasMadre(ByVal leerCuentasMadreRequest As leerCuentasMadreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("leerCuentasMadre", New Object() {leerCuentasMadreRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndleerCuentasMadre(ByVal asyncResult As System.IAsyncResult) As leerCuentasMadreResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),leerCuentasMadreResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaspostpagows/leerDatosBloqueoLinea", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function leerDatosBloqueoLinea(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> ByVal leerDatosBloqueoLineaRequest As leerDatosBloqueoLineaRequest) As <System.Xml.Serialization.XmlElementAttribute("leerDatosBloqueoLineaResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> leerDatosBloqueoLineaResponse
            Dim results() As Object = Me.Invoke("leerDatosBloqueoLinea", New Object() {leerDatosBloqueoLineaRequest})
            Return CType(results(0),leerDatosBloqueoLineaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginleerDatosBloqueoLinea(ByVal leerDatosBloqueoLineaRequest As leerDatosBloqueoLineaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("leerDatosBloqueoLinea", New Object() {leerDatosBloqueoLineaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndleerDatosBloqueoLinea(ByVal asyncResult As System.IAsyncResult) As leerDatosBloqueoLineaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),leerDatosBloqueoLineaResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaspostpagows/leerDetalleLlamadasNoFacturado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function leerDetalleLlamadasNoFacturado(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> ByVal leerDetalleLlamadasNoFacturadoRequest As leerDetalleLlamadasNoFacturadoRequest) As <System.Xml.Serialization.XmlElementAttribute("leerDetalleLlamadasNoFacturadoResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> leerDetalleLlamadasNoFacturadoResponse
            Dim results() As Object = Me.Invoke("leerDetalleLlamadasNoFacturado", New Object() {leerDetalleLlamadasNoFacturadoRequest})
            Return CType(results(0),leerDetalleLlamadasNoFacturadoResponse)
        End Function
        
        '<remarks/>
        Public Function BeginleerDetalleLlamadasNoFacturado(ByVal leerDetalleLlamadasNoFacturadoRequest As leerDetalleLlamadasNoFacturadoRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("leerDetalleLlamadasNoFacturado", New Object() {leerDetalleLlamadasNoFacturadoRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndleerDetalleLlamadasNoFacturado(ByVal asyncResult As System.IAsyncResult) As leerDetalleLlamadasNoFacturadoResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),leerDetalleLlamadasNoFacturadoResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaspostpagows/leerIccidAsociadosALinea", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function leerIccidAsociadosALinea(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> ByVal leerIccidAsociadosALineaRequest As leerIccidAsociadosALineaRequest) As <System.Xml.Serialization.XmlElementAttribute("leerIccidAsociadosALineaResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> leerIccidAsociadosALineaResponse
            Dim results() As Object = Me.Invoke("leerIccidAsociadosALinea", New Object() {leerIccidAsociadosALineaRequest})
            Return CType(results(0),leerIccidAsociadosALineaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginleerIccidAsociadosALinea(ByVal leerIccidAsociadosALineaRequest As leerIccidAsociadosALineaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("leerIccidAsociadosALinea", New Object() {leerIccidAsociadosALineaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndleerIccidAsociadosALinea(ByVal asyncResult As System.IAsyncResult) As leerIccidAsociadosALineaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),leerIccidAsociadosALineaResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaspostpagows/leerSubCuentasPorCuenta", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function leerSubCuentasPorCuenta(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> ByVal leerSubCuentasPorCuentaRequest As leerSubCuentasPorCuentaRequest) As <System.Xml.Serialization.XmlElementAttribute("leerSubCuentasPorCuentaResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")> leerSubCuentasPorCuentaResponse
            Dim results() As Object = Me.Invoke("leerSubCuentasPorCuenta", New Object() {leerSubCuentasPorCuentaRequest})
            Return CType(results(0),leerSubCuentasPorCuentaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginleerSubCuentasPorCuenta(ByVal leerSubCuentasPorCuentaRequest As leerSubCuentasPorCuentaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("leerSubCuentasPorCuenta", New Object() {leerSubCuentasPorCuentaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndleerSubCuentasPorCuenta(ByVal asyncResult As System.IAsyncResult) As leerSubCuentasPorCuentaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),leerSubCuentasPorCuentaResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class datosClienteRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public custcode As String
        
        '<remarks/>
        Public dnnum As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class auditRequestType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public nombreAplicacion As String
        
        '<remarks/>
        Public usuarioAplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class SubCuentaType
        
        '<remarks/>
        Public cuentaPadre As String
        
        '<remarks/>
        Public cuenta As String
    
    '<remarks/>
        Public customerId As String
        
        '<remarks/>
        Public nombre As String
        
        '<remarks/>
        Public apellidos As String
        
        '<remarks/>
        Public estado As String
    
    '<remarks/>
        Public nivel As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerSubCuentasPorCuentaResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("SubCuentaResponseType", IsNullable:=false)>  _
        Public listaSubCuentas() As SubCuentaType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class auditResponseType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoRespuesta As String
        
        '<remarks/>
        Public mensajeRespuesta As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class parametrosTypeObjetoOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public campo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerSubCuentasPorCuentaRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public numeroCuenta As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class IccidType
        
        '<remarks/>
        Public numeroIccid As String
        
        '<remarks/>
        Public linea As String
        
        '<remarks/>
        Public estado As String
        
        '<remarks/>
        Public fechaAsignacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerIccidAsociadosALineaResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("iccidResponseType", IsNullable:=false)>  _
        Public listaIccids() As IccidType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerIccidAsociadosALineaRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public numeroIccid As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class LlamadaType
        
        '<remarks/>
        Public fechaHoraInicio As String
        
        '<remarks/>
        Public telefonoDestino As String
        
        '<remarks/>
        Public duracion As String
        
        '<remarks/>
        Public tipoServicio As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public destino As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerDetalleLlamadasNoFacturadoResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("LlamadaResponseType", IsNullable:=false)>  _
        Public listaLlamadas() As LlamadaType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerDetalleLlamadasNoFacturadoRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public tipoConsulta As String
        
        '<remarks/>
        Public valor As String
        
        '<remarks/>
        Public fechaInicio As String
        
        '<remarks/>
        Public fechaFin As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class InformacionBloqueoType
        
        '<remarks/>
        Public cuenta As String
        
        '<remarks/>
        Public codigoTickler As String
        
        '<remarks/>
        Public estadoAnotacion As String
        
        '<remarks/>
        Public prioridad As String
        
        '<remarks/>
        Public descripcionCorta As String
        
        '<remarks/>
        Public usuarioSeguimiento As String
        
        '<remarks/>
        Public fechaSeguimiento As String
        
        '<remarks/>
        Public accionSeguimiento As String
        
        '<remarks/>
        Public fechaApertura As String
        
        '<remarks/>
        Public fechaCierre As String
        
        '<remarks/>
        Public nroTickler As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerDatosBloqueoLineaResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("InformacionBloqueoResponseType", IsNullable:=false)>  _
        Public listaInformacionBloqueos() As InformacionBloqueoType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerDatosBloqueoLineaRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public customerId As String
        
        '<remarks/>
        Public coId As String
        
        '<remarks/>
        Public cstype As String
        
        '<remarks/>
        Public ticklerNumber As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class CuentaMadreType
        
        '<remarks/>
        Public idCuentaMadre As String
        
        '<remarks/>
        Public descripcion As String
        
        '<remarks/>
        Public nivel As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerCuentasMadreResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("CuentaMadreResponseType", IsNullable:=false)>  _
        Public listaCuentasMadre() As CuentaMadreType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class leerCuentasMadreRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public telefono As String
        
        '<remarks/>
        Public cuenta As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class objetoServicioType
        
        '<remarks/>
        Public codigo As String
        
        '<remarks/>
        Public descripcion As String
        
        '<remarks/>
        Public estado As String
        
        '<remarks/>
        Public fecha_estado As String
        
        '<remarks/>
        Public fecha_solicitud As String
        
        '<remarks/>
        Public cuota As String
        
        '<remarks/>
        Public paquete As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class datosServicioType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoServicio", IsNullable:=false)>  _
        Public listaDatosServicios() As objetoServicioType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class serviciosLineaResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        Public datosServicio As datosServicioType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class serviciosLineaRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public p_coid As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class objetoContratoType
        
        '<remarks/>
        Public telefono As String
        
        '<remarks/>
        Public estado As String
        
        '<remarks/>
        Public motivo As String
        
        '<remarks/>
        Public fec_estado As String
        
        '<remarks/>
        Public plan As String
        
        '<remarks/>
        Public plazo_contrato As String
        
        '<remarks/>
        Public iccid As String
        
        '<remarks/>
        Public imsi As String
        
        '<remarks/>
        Public campania As String
        
        '<remarks/>
        Public p_venta As String
        
        '<remarks/>
        Public nicho_id As String
        
        '<remarks/>
        Public vendedor As String
        
        '<remarks/>
        Public co_id As String
        
        '<remarks/>
        Public fecha_act As String
        
        '<remarks/>
        Public flag_plataforma As String
        
        '<remarks/>
        Public pin1 As String
        
        '<remarks/>
        Public puk1 As String
        
        '<remarks/>
        Public pin2 As String
        
        '<remarks/>
        Public puk2 As String
        
        '<remarks/>
        Public codigo_plan_tarifario As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class datosContratoType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoContrato", IsNullable:=false)>  _
        Public listaDatosContratos() As objetoContratoType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class datosContratoResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        Public datosContrato As datosContratoType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class datosContratoRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public p_coid As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class objetoClienteType
        
        '<remarks/>
        Public customerId As String
        
        '<remarks/>
        Public cuenta As String
        
        '<remarks/>
        Public nombre As String
        
        '<remarks/>
        Public apellidos As String
        
        '<remarks/>
        Public razonSocial As String
        
        '<remarks/>
        Public tip_doc As String
        
        '<remarks/>
        Public num_doc As String
        
        '<remarks/>
        Public titulo As String
        
        '<remarks/>
        Public telef_principal As String
        
        '<remarks/>
        Public estado_civil As String
        
        '<remarks/>
        Public fecha_nac As String
        
        '<remarks/>
        Public lug_nac As String
        
        '<remarks/>
        Public ruc_dni As String
        
        '<remarks/>
        Public nomb_comercial As String
        
        '<remarks/>
        Public contacto_cliente As String
        
        '<remarks/>
        Public rep_legal As String
        
        '<remarks/>
        Public telef_contacto As String
        
        '<remarks/>
        Public fax As String
        
        '<remarks/>
        Public email As String
        
        '<remarks/>
        Public cargo As String
        
        '<remarks/>
        Public consultor As String
        
        '<remarks/>
        Public asesor As String
        
        '<remarks/>
        Public direccion_fac As String
        
        '<remarks/>
        Public urbanizacion_fac As String
        
        '<remarks/>
        Public distrito_fac As String
        
        '<remarks/>
        Public provincia_fac As String
        
        '<remarks/>
        Public cod_postal_fac As String
        
        '<remarks/>
        Public departamento_fac As String
        
        '<remarks/>
        Public pais_fac As String
        
        '<remarks/>
        Public direccion_leg As String
        
        '<remarks/>
        Public urbanizacion_leg As String
        
        '<remarks/>
        Public distrito_leg As String
        
        '<remarks/>
        Public provincia_leg As String
        
        '<remarks/>
        Public cod_postal_leg As String
        
        '<remarks/>
        Public departamento_leg As String
        
        '<remarks/>
        Public pais_leg As String
        
        '<remarks/>
        Public co_id As String
        
        '<remarks/>
        Public nicho_id As String
        
        '<remarks/>
        Public num_cuentas As String
        
        '<remarks/>
        Public num_lineas As String
        
        '<remarks/>
        Public ciclo_fac As String
        
        '<remarks/>
        Public status_cuenta As String
        
        '<remarks/>
        Public modalidad As String
        
        '<remarks/>
        Public tipo_cliente As String
        
        '<remarks/>
        Public fecha_act As String
        
        '<remarks/>
        Public limite_credito As String
        
        '<remarks/>
        Public segmento As String
        
        '<remarks/>
        Public respon_pago As String
        
        '<remarks/>
        Public credit_score As String
        
        '<remarks/>
        Public forma_pago As String
        
        '<remarks/>
        Public codigo_tipo_cliente As String
        
        '<remarks/>
        Public sexo As String
        
        '<remarks/>
        Public nacionalidad As String
        
        '<remarks/>
        Public estado_civil_id As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class datosClienteType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoCliente", IsNullable:=false)>  _
        Public listaDatosClientes() As objetoClienteType
        
        '<remarks/>
        Public errorsql As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaspostpagows/types")>  _
    Public Class datosClienteResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        Public datosCliente As datosClienteType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
End Namespace
