//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
// 
namespace NEGOCIO_SIC_SANS.AccionesPostPagoWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DevIntWSSoapBinding", Namespace="http://pe/com/claro/esb/services/devInt/process/ws")]
    public class DevIntWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DevIntWS() {
            this.Url = "http://limdeseaiv24.tim.com.pe:8909/DevIntProcess/EbsAccionesPostPagoWS";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/devInt/process/ws", ResponseNamespace="http://pe/com/claro/esb/services/devInt/process/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ValidaCambioNumeroResponse.Output", Namespace="pe/com/claro/services/postpago/schemas/ValidaCambioNumeroResponse")]
        public ValidaCambioNumeroResponseOutput validaCambioNumero([System.Xml.Serialization.XmlElementAttribute("ValidaCambioNumeroRequest.Input", Namespace="pe/com/claro/services/postpago/schemas/ValidaCambioNumeroRequest")] ValidaCambioNumeroRequestInput ValidaCambioNumeroRequestInput) {
            object[] results = this.Invoke("validaCambioNumero", new object[] {
                        ValidaCambioNumeroRequestInput});
            return ((ValidaCambioNumeroResponseOutput)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginvalidaCambioNumero(ValidaCambioNumeroRequestInput ValidaCambioNumeroRequestInput, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("validaCambioNumero", new object[] {
                        ValidaCambioNumeroRequestInput}, callback, asyncState);
        }
        
        /// <remarks/>
        public ValidaCambioNumeroResponseOutput EndvalidaCambioNumero(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ValidaCambioNumeroResponseOutput)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/devInt/process/ws", ResponseNamespace="http://pe/com/claro/esb/services/devInt/process/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CambioNumeroResponse.Output", Namespace="pe/com/claro/services/postpago/schemas/CambiaNumeroPostPagoResponse")]
        public CambioNumeroResponseOutput cambiaNumeroPostpago([System.Xml.Serialization.XmlElementAttribute("CambioNumeroRequest.Input", Namespace="pe/com/claro/services/postpago/schemas/CambiaNumeroPostPagoRequest")] CambioNumeroRequestInput CambioNumeroRequestInput) {
            object[] results = this.Invoke("cambiaNumeroPostpago", new object[] {
                        CambioNumeroRequestInput});
            return ((CambioNumeroResponseOutput)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincambiaNumeroPostpago(CambioNumeroRequestInput CambioNumeroRequestInput, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cambiaNumeroPostpago", new object[] {
                        CambioNumeroRequestInput}, callback, asyncState);
        }
        
        /// <remarks/>
        public CambioNumeroResponseOutput EndcambiaNumeroPostpago(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CambioNumeroResponseOutput)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/devInt/process/ws", ResponseNamespace="http://pe/com/claro/esb/services/devInt/process/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int borrarProgramacion(string msisdn, int codigo, string estado) {
            object[] results = this.Invoke("borrarProgramacion", new object[] {
                        msisdn,
                        codigo,
                        estado});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginborrarProgramacion(string msisdn, int codigo, string estado, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("borrarProgramacion", new object[] {
                        msisdn,
                        codigo,
                        estado}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndborrarProgramacion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe/com/claro/services/postpago/schemas/ValidaCambioNumeroRequest")]
    public class ValidaCambioNumeroRequestInput {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DETALLEINPUTType Request;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe/com/claro/services/postpago/schemas/ValidaCambioNumeroRequest")]
    public class DETALLEINPUTType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FLAGID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHAEJECUCION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DETALLEType", Namespace="pe/com/claro/services/postpago/schemas/CambiaNumeroPostPagoResponse")]
    public class DETALLEType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ERRORCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRORDESC;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe/com/claro/services/postpago/schemas/CambiaNumeroPostPagoResponse")]
    public class CambioNumeroResponseOutput {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DETALLEType1 ERROR;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DETALLEINPUTType", Namespace="pe/com/claro/services/postpago/schemas/CambiaNumeroPostPagoRequest")]
    public class DETALLEINPUTType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMERONUEVO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHAEJECUCION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESTRASLADO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Double COSTO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FLAGID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMEROACTUAL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODIGOAPLICATIVO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORDAPLICATIVO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODIGOUSUARIO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COSTMEDNO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FLAGCAMBIOCHIPNUME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FLAGLOCUCION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe/com/claro/services/postpago/schemas/CambiaNumeroPostPagoRequest")]
    public class CambioNumeroRequestInput {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DETALLEINPUTType1 Request;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe/com/claro/services/postpago/schemas/ValidaCambioNumeroResponse")]
    public class DETALLEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ERRORCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRORDESC;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe/com/claro/services/postpago/schemas/ValidaCambioNumeroResponse")]
    public class ValidaCambioNumeroResponseOutput {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DETALLEType ERROR;
    }
}
