'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace ConsultarPuntosWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ebsConsultatPuntosClaroClubPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")>  _
    Public Class ebsConsultaPuntosClaroClubService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv15.tim.com.pe:8901/ClaroClub_Services/Inquiry/ConsultaPuntos"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ebsConsultarPuntosClaroClub/consultarPuntosClaroClub", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function consultarPuntosClaroClub(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")> ByVal consultarPuntosRequest As consultarPuntosRequest) As <System.Xml.Serialization.XmlElementAttribute("consultarPuntosResponse", [Namespace]:="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")> consultarPuntosResponse
            Dim results() As Object = Me.Invoke("consultarPuntosClaroClub", New Object() {consultarPuntosRequest})
            Return CType(results(0),consultarPuntosResponse)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarPuntosClaroClub(ByVal consultarPuntosRequest As consultarPuntosRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarPuntosClaroClub", New Object() {consultarPuntosRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarPuntosClaroClub(ByVal asyncResult As System.IAsyncResult) As consultarPuntosResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),consultarPuntosResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")>  _
    Public Class consultarPuntosRequest
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public aplicacion As String
        
        '<remarks/>
        Public usuarioAplicacion As String
        
        '<remarks/>
        Public tipoDoc As String
        
        '<remarks/>
        Public numDoc As String
        
        '<remarks/>
        Public codigoCliente As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")>  _
    Public Class CurCampanaType
        
        '<remarks/>
        Public idCampana As Integer
        
        '<remarks/>
        Public descripcion As String
        
        '<remarks/>
        Public tipo As String
        
        '<remarks/>
        Public valor As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public fecha_inicio As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public fecha_fin As Date
        
        '<remarks/>
        Public tipoCliente As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")>  _
    Public Class CursorSaldosType
        
        '<remarks/>
        Public tipoCliente As String
        
        '<remarks/>
        Public saldoTT As String
        
        '<remarks/>
        Public saldoCC As String
        
        '<remarks/>
        Public saldoIB As String
        
        '<remarks/>
        Public solesTT As String
        
        '<remarks/>
        Public valorSegmento As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/servicecommons/")>  _
    Public Class AuditType
        
        '<remarks/>
        Public txId As String
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public errorMsg As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/claroclubservices/consultarpuntosclaroclub")>  _
    Public Class consultarPuntosResponse
        
        '<remarks/>
        Public audit As AuditType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("cursorSaldos")>  _
        Public cursorSaldos() As CursorSaldosType
        
        '<remarks/>
        Public factorConversion As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("curCampana")>  _
        Public curCampana() As CurCampanaType
        
        '<remarks/>
        Public codigoSegmento As String
    End Class
End Namespace
