'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
'
Namespace ActivacionPostpagoWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ActivaAcuerdoServiceSoapBinding", [Namespace]:="http://pe/com/claro/esb/services/activacionespostpago/ws")>  _
    Public Class ActivaAcuerdoService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv06.tim.com.pe:8909/ActivacionesPostpagoProcess/ActivaAcuerdo"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/activacionespostpago/ws", ResponseNamespace:="http://pe/com/claro/esb/services/activacionespostpago/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function activaAcuerdo(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")> ByVal callservice As callservice) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("activaAcuerdo", New Object() {callservice})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginactivaAcuerdo(ByVal callservice As callservice, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("activaAcuerdo", New Object() {callservice}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndactivaAcuerdo(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callservice
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public header As callserviceHeader
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public datos As callserviceDatos
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceHeader
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public cliente As callserviceHeaderCliente
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public servicio As callserviceHeaderServicio
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceHeaderCliente
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public servicio As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
        Public timeout As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public clave As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public aplicacion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public timestamp As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idsrv As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("filterClass", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public filterClass() As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceDatosTablaFilaParametro
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public nombre As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public modo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceDatosTabla
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), _
         System.Xml.Serialization.XmlArrayItemAttribute("parametro", GetType(callserviceDatosTablaFilaParametro), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=False)> _
        Public fila() As callserviceDatosTablaFilaParametro
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public nombre As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceDatosParametro
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public nombre As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public modo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceDatos
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametro", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public parametro() As callserviceDatosParametro
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("tabla", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public tabla() As callserviceDatosTabla
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceHeaderServicioRetcode
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public modo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As System.SByte
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public valorSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceHeaderServicio
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public retcode As callserviceHeaderServicioRetcode
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public errdesc As String
    End Class
End Namespace
