'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
'
Namespace RenovacionModemPrepagoWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ebsRenovacionModemPrepagoPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/esb/services/postventa/renovacionmodemprepago")>  _
    Public Class ebsRenovacionModemPrepagoService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv13.tim.com.pe:7909/RenovacionModemPrepagoWS/ebsRenovacionModemPr"& _ 
"epago"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/postventa/renovacionmodemprepago/renovarPlanModem", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function renovarPlanModem(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/esb/services/postventa/renovacionmodemprepago")> ByVal renovarPlanModemRequest As renovarPlanModemRequest) As <System.Xml.Serialization.XmlElementAttribute("renovarPlanModemResponse", [Namespace]:="http://claro.com.pe/eai/esb/services/postventa/renovacionmodemprepago")> renovarPlanModemResponse
            Dim results() As Object = Me.Invoke("renovarPlanModem", New Object() {renovarPlanModemRequest})
            Return CType(results(0),renovarPlanModemResponse)
        End Function
        
        '<remarks/>
        Public Function BeginrenovarPlanModem(ByVal renovarPlanModemRequest As renovarPlanModemRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("renovarPlanModem", New Object() {renovarPlanModemRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndrenovarPlanModem(ByVal asyncResult As System.IAsyncResult) As renovarPlanModemResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),renovarPlanModemResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/esb/services/postventa/renovacionmodemprepago")>  _
    Public Class renovarPlanModemRequest
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public nombreAplicacion As String
        
        '<remarks/>
        Public usrAplicacion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public msisdn As String
        
        '<remarks/>
        Public codigoPromocion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/esb/services/postventa/renovacionmodemprepago")>  _
    Public Class renovarPlanModemResponse
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoRespuesta As String
        
        '<remarks/>
        Public mensajeRespuesta As String
    End Class
End Namespace
