'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace GestionReposicionWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GestionCambioSIMPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws")>  _
    Public Class GestionCambioSIMService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv28.tim.com.pe:8909/GestionCambioSIM/ebsGestionCambioSIMSB11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/validarNuevoSIM", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function validarNuevoSIM(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")> ByVal validarNuevoSIMRequest As validarNuevoSIMRequest) As <System.Xml.Serialization.XmlElementAttribute("validarNuevoSIMResponse", [Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")> validarNuevoSIMResponse
            Dim results() As Object = Me.Invoke("validarNuevoSIM", New Object() {validarNuevoSIMRequest})
            Return CType(results(0),validarNuevoSIMResponse)
        End Function
        
        '<remarks/>
        Public Function BeginvalidarNuevoSIM(ByVal validarNuevoSIMRequest As validarNuevoSIMRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("validarNuevoSIM", New Object() {validarNuevoSIMRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndvalidarNuevoSIM(ByVal asyncResult As System.IAsyncResult) As validarNuevoSIMResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),validarNuevoSIMResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/validarEjecutarReposic"& _ 
"ion", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function validarEjecutarReposicion(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")> ByVal validarEjecutarReposicionRequest As validarEjecutarReposicionRequest) As <System.Xml.Serialization.XmlElementAttribute("validarEjecutarReposicionResponse", [Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")> validarEjecutarReposicionResponse
            Dim results() As Object = Me.Invoke("validarEjecutarReposicion", New Object() {validarEjecutarReposicionRequest})
            Return CType(results(0),validarEjecutarReposicionResponse)
        End Function
        
        '<remarks/>
        Public Function BeginvalidarEjecutarReposicion(ByVal validarEjecutarReposicionRequest As validarEjecutarReposicionRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("validarEjecutarReposicion", New Object() {validarEjecutarReposicionRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndvalidarEjecutarReposicion(ByVal asyncResult As System.IAsyncResult) As validarEjecutarReposicionResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),validarEjecutarReposicionResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/validar4G", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function validar4G(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")> ByVal validar4GRequest As validar4GRequest) As <System.Xml.Serialization.XmlElementAttribute("validar4GResponse", [Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")> validar4GResponse
            Dim results() As Object = Me.Invoke("validar4G", New Object() {validar4GRequest})
            Return CType(results(0),validar4GResponse)
        End Function
        
        '<remarks/>
        Public Function Beginvalidar4G(ByVal validar4GRequest As validar4GRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("validar4G", New Object() {validar4GRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endvalidar4G(ByVal asyncResult As System.IAsyncResult) As validar4GResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),validar4GResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/encolarReposiciones", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function encolarReposiciones(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")> ByVal encolarReposicionesRequest As encolarReposicionesRequest) As <System.Xml.Serialization.XmlElementAttribute("encolarReposicionesResponse", [Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")> encolarReposicionesResponse
            Dim results() As Object = Me.Invoke("encolarReposiciones", New Object() {encolarReposicionesRequest})
            Return CType(results(0),encolarReposicionesResponse)
        End Function
        
        '<remarks/>
        Public Function BeginencolarReposiciones(ByVal encolarReposicionesRequest As encolarReposicionesRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("encolarReposiciones", New Object() {encolarReposicionesRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndencolarReposiciones(ByVal asyncResult As System.IAsyncResult) As encolarReposicionesResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),encolarReposicionesResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class validarNuevoSIMRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auditRequest As parametrosAuditRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public iccid As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objetoRequestOpcional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosRequestObjetoRequestOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class parametrosAuditRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idTransaccion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public ipAplicacion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public nombreAplicacion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuarioAplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class encolarReposicionesResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auditResponse As parametrosAuditResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objetoResponseOpcional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosResponseObjetoResponseOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class parametrosAuditResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idTransaccion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public codigoRespuesta As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public mensajeRespuesta As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class parametrosResponseObjetoResponseOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public campo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class encolarReposicionesRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auditRequest As parametrosAuditRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public datosLineas As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objetoRequestOpcional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosRequestObjetoRequestOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class parametrosRequestObjetoRequestOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public campo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class validar4GResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auditResponse As parametrosAuditResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public hlr As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public estado4GLinea As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public compatibilidad As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public codigoRespuestaValidacion4G As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public mensajeRespuestaValidacion4G As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public flagActiva4G As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objetoResponseOpcional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosResponseObjetoResponseOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class validar4GRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auditRequest As parametrosAuditRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public msisdn As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objetoRequestOpcional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosRequestObjetoRequestOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class validarEjecutarReposicionResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auditResponse As parametrosAuditResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public codigoRespuestaValidacion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public mensajeRespuestaValidacion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public codigoRespuestaReposicion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public mensajeRespuestaReposicion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public estadoLinea As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public coId As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public customerId As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public tipoBloqueo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objetoResponseOpcional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosResponseObjetoResponseOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class validarEjecutarReposicionRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auditRequest As parametrosAuditRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public msisdn As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public tipoDoc As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public nroDoc As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public iccid As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public flagEjecucionReposicion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objetoRequestOpcional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosRequestObjetoRequestOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/postventa/hlr/gestioncambiosim/ws/types")>  _
    Public Class validarNuevoSIMResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auditResponse As parametrosAuditResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objetoResponseOpcional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosResponseObjetoResponseOpcional
    End Class
End Namespace
