'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace WSProcesaVentaActivacionOlo
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProcesaVentaActivacionOloWSPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ws/venta/procesaventaactivacionolows")>  _
    Public Class ProcesaVentaActivacionOloWSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.100.152:8901/ProcesaVentaActivacionOloWS/procesaVentaActivacionOlo"& _ 
"SOAP11Port"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/venta/procesaventaactivacionolows/procesarVentaActivac"& _ 
"ion", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function procesarVentaActivacion(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/venta/procesaventaactivacionolows/procesaventaactivaci"& _ 
"on/")> ByVal procesarVentaActivacionRequest As procesarVentaActivacionRequest) As <System.Xml.Serialization.XmlElementAttribute("procesarVentaActivacionResponse", [Namespace]:="http://claro.com.pe/eai/ws/venta/procesaventaactivacionolows/procesaventaactivaci"& _ 
"on/")> procesarVentaActivacionResponse
            Dim results() As Object = Me.Invoke("procesarVentaActivacion", New Object() {procesarVentaActivacionRequest})
            Return CType(results(0),procesarVentaActivacionResponse)
        End Function
        
        '<remarks/>
        Public Function BeginprocesarVentaActivacion(ByVal procesarVentaActivacionRequest As procesarVentaActivacionRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("procesarVentaActivacion", New Object() {procesarVentaActivacionRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndprocesarVentaActivacion(ByVal asyncResult As System.IAsyncResult) As procesarVentaActivacionResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),procesarVentaActivacionResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/venta/procesaventaactivacionolows/procesaventaactivaci"& _ 
"on/")>  _
    Public Class procesarVentaActivacionRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public tipoDocumento As String
        
        '<remarks/>
        Public nroDocumento As String
        
        '<remarks/>
        Public idPedido As String
        
        '<remarks/>
        Public idVenta As String
        
        '<remarks/>
        Public idRecarga As String
        
        '<remarks/>
        Public tipoOperacion As String
        
        '<remarks/>
        Public serviceId As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class auditRequestType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public nombreAplicacion As String
        
        '<remarks/>
        Public usuarioAplicacion As String
        
        '<remarks/>
        Public msgid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class auditResponseType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoRespuesta As String
        
        '<remarks/>
        Public mensajeRespuesta As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/venta/procesaventaactivacionolows/procesaventaactivaci"& _ 
"on/")>  _
    Public Class procesarVentaActivacionResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class parametrosTypeObjetoOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public campo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
End Namespace
