'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
'
Namespace WSPlanPrepagoEspecial
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ebsCambioPlanPrepagoEspecialPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/postventa/cambioplanprepagoespecial")>  _
    Public Class ebsCambioPlanPrepagoEspecialService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv13.tim.com.pe:7909/CambioPlanPrepagoEspecialWS/ebsCambioPlanPrep"& _ 
"agoEspecialPort11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/postventa/cambioplanprepagoespecial/cambiarPlanPrepagoEsp"& _ 
"ecial", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function cambiarPlanPrepagoEspecial(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/postventa/cambioplanprepagoespecial")> ByVal cambiarPlanPrepagoEspecialRequest As cambiarPlanPrepagoEspecialRequest) As <System.Xml.Serialization.XmlElementAttribute("cambiarPlanPrepagoEspecialResponse", [Namespace]:="http://claro.com.pe/eai/postventa/cambioplanprepagoespecial")> cambiarPlanPrepagoEspecialResponse
            Dim results() As Object = Me.Invoke("cambiarPlanPrepagoEspecial", New Object() {cambiarPlanPrepagoEspecialRequest})
            Return CType(results(0),cambiarPlanPrepagoEspecialResponse)
        End Function
        
        '<remarks/>
        Public Function BegincambiarPlanPrepagoEspecial(ByVal cambiarPlanPrepagoEspecialRequest As cambiarPlanPrepagoEspecialRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("cambiarPlanPrepagoEspecial", New Object() {cambiarPlanPrepagoEspecialRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcambiarPlanPrepagoEspecial(ByVal asyncResult As System.IAsyncResult) As cambiarPlanPrepagoEspecialResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),cambiarPlanPrepagoEspecialResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/postventa/cambioplanprepagoespecial")>  _
    Public Class cambiarPlanPrepagoEspecialRequest
        
        '<remarks/>
        Public audit As AuditType
        
        '<remarks/>
        Public msisdn As String
        
        '<remarks/>
        Public offer As String
        
        '<remarks/>
        Public subscriberStatus As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("listaOpcional", IsNullable:=false)>  _
        Public listaRequestOpcional() As ListaOpcionalTypeListaOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/postventa/cambioplanprepagoespecial")>  _
    Public Class AuditType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public nombreAplicacion As String
        
        '<remarks/>
        Public usuarioAplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/postventa/cambioplanprepagoespecial")>  _
    Public Class cambiarPlanPrepagoEspecialResponse
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoRetorno As String
        
        '<remarks/>
        Public descripcionRetorno As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/postventa/cambioplanprepagoespecial")>  _
    Public Class ListaOpcionalTypeListaOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public clave As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
End Namespace
