//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2503
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
// 
namespace SwichTransaccional.TransaccionPagoDRAWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransaccionPagoDRA", Namespace="http://claro.com.pe/eai/oac/transaccionpagodra/")]
    public class TransaccionPagoDRA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public TransaccionPagoDRA() {
            this.Url = "http://limdeseaiv15.tim.com.pe:8901/OAC_Services/Transaction/TransaccionPagoDocRe" +
"ntaAdelantada";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/oac/transaccionpagodra/crearPagoDRA", RequestNamespace="http://claro.com.pe/eai/oac/transaccionpagodra/", ResponseNamespace="http://claro.com.pe/eai/oac/transaccionpagodra/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("NRO_OPE_PAGO_SISACT")]
        public string crearPagoDRA(
                    ref string txId, 
                    string COD_APLICACION, 
                    string USUARIO_APLICACION, 
                    string COD_PAGO_DRA, 
                    string TIPO_DOCUMENTO, 
                    string NRO_DOCUMENTO, 
                    string DESCRIPCION_DOCUMENTO, 
                    string COD_MONEDA, 
                    System.Decimal IMPORTE_PAGO, 
                    System.DateTime FEC_PAGO, 
                    string TRACE_ID, 
                    string NRO_OPE_PAGO, 
                    string COD_BANCO, 
                    string COD_PDV, 
                    string LISTA_MEDIO_PAGO, 
                    System.Decimal IMPORTE_TOTAL_PAGO, 
                    out string COD_RPTA, 
                    out string MSG_RPTA) {
            object[] results = this.Invoke("crearPagoDRA", new object[] {
                        txId,
                        COD_APLICACION,
                        USUARIO_APLICACION,
                        COD_PAGO_DRA,
                        TIPO_DOCUMENTO,
                        NRO_DOCUMENTO,
                        DESCRIPCION_DOCUMENTO,
                        COD_MONEDA,
                        IMPORTE_PAGO,
                        FEC_PAGO,
                        TRACE_ID,
                        NRO_OPE_PAGO,
                        COD_BANCO,
                        COD_PDV,
                        LISTA_MEDIO_PAGO,
                        IMPORTE_TOTAL_PAGO});
            txId = ((string)(results[1]));
            COD_RPTA = ((string)(results[2]));
            MSG_RPTA = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincrearPagoDRA(
                    string txId, 
                    string COD_APLICACION, 
                    string USUARIO_APLICACION, 
                    string COD_PAGO_DRA, 
                    string TIPO_DOCUMENTO, 
                    string NRO_DOCUMENTO, 
                    string DESCRIPCION_DOCUMENTO, 
                    string COD_MONEDA, 
                    System.Decimal IMPORTE_PAGO, 
                    System.DateTime FEC_PAGO, 
                    string TRACE_ID, 
                    string NRO_OPE_PAGO, 
                    string COD_BANCO, 
                    string COD_PDV, 
                    string LISTA_MEDIO_PAGO, 
                    System.Decimal IMPORTE_TOTAL_PAGO, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return this.BeginInvoke("crearPagoDRA", new object[] {
                        txId,
                        COD_APLICACION,
                        USUARIO_APLICACION,
                        COD_PAGO_DRA,
                        TIPO_DOCUMENTO,
                        NRO_DOCUMENTO,
                        DESCRIPCION_DOCUMENTO,
                        COD_MONEDA,
                        IMPORTE_PAGO,
                        FEC_PAGO,
                        TRACE_ID,
                        NRO_OPE_PAGO,
                        COD_BANCO,
                        COD_PDV,
                        LISTA_MEDIO_PAGO,
                        IMPORTE_TOTAL_PAGO}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcrearPagoDRA(System.IAsyncResult asyncResult, out string txId, out string COD_RPTA, out string MSG_RPTA) {
            object[] results = this.EndInvoke(asyncResult);
            txId = ((string)(results[1]));
            COD_RPTA = ((string)(results[2]));
            MSG_RPTA = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/oac/transaccionpagodra/anularPagoDRA", RequestNamespace="http://claro.com.pe/eai/oac/transaccionpagodra/", ResponseNamespace="http://claro.com.pe/eai/oac/transaccionpagodra/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("NRO_OPE_ANULACION")]
        public string anularPagoDRA(ref string txId, string COD_APLICACION, string USUARIO_APLICACION, string NRO_OPE_PAGO, out string COD_RPTA, out string MSG_RPTA) {
            object[] results = this.Invoke("anularPagoDRA", new object[] {
                        txId,
                        COD_APLICACION,
                        USUARIO_APLICACION,
                        NRO_OPE_PAGO});
            txId = ((string)(results[1]));
            COD_RPTA = ((string)(results[2]));
            MSG_RPTA = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginanularPagoDRA(string txId, string COD_APLICACION, string USUARIO_APLICACION, string NRO_OPE_PAGO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("anularPagoDRA", new object[] {
                        txId,
                        COD_APLICACION,
                        USUARIO_APLICACION,
                        NRO_OPE_PAGO}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndanularPagoDRA(System.IAsyncResult asyncResult, out string txId, out string COD_RPTA, out string MSG_RPTA) {
            object[] results = this.EndInvoke(asyncResult);
            txId = ((string)(results[1]));
            COD_RPTA = ((string)(results[2]));
            MSG_RPTA = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/oac/transaccionpagodra/extornoPagoDRA", RequestNamespace="http://claro.com.pe/eai/oac/transaccionpagodra/", ResponseNamespace="http://claro.com.pe/eai/oac/transaccionpagodra/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("NRO_OPE_PAGO")]
        public string extornoPagoDRA(ref string txId, string COD_APLICACION, string USUARIO_APLICACION, string TRACE_ID, out string COD_RPTA, out string MSG_RPTA) {
            object[] results = this.Invoke("extornoPagoDRA", new object[] {
                        txId,
                        COD_APLICACION,
                        USUARIO_APLICACION,
                        TRACE_ID});
            txId = ((string)(results[1]));
            COD_RPTA = ((string)(results[2]));
            MSG_RPTA = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginextornoPagoDRA(string txId, string COD_APLICACION, string USUARIO_APLICACION, string TRACE_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("extornoPagoDRA", new object[] {
                        txId,
                        COD_APLICACION,
                        USUARIO_APLICACION,
                        TRACE_ID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndextornoPagoDRA(System.IAsyncResult asyncResult, out string txId, out string COD_RPTA, out string MSG_RPTA) {
            object[] results = this.EndInvoke(asyncResult);
            txId = ((string)(results[1]));
            COD_RPTA = ((string)(results[2]));
            MSG_RPTA = ((string)(results[3]));
            return ((string)(results[0]));
        }
    }
}
