'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

' 
' This source code was auto-generated by wsdl, Version=1.1.4322.573.
' 
Option Strict Off
Option Explicit On 

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Namespace RegistroMetricasVentaWS


    ''' <remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
        System.ComponentModel.DesignerCategoryAttribute("code"), _
        System.Web.Services.WebServiceBindingAttribute(Name:="ebsMigracionSaldoGSMPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/ebs/ws/venta/MigracionSaldoGSM")> _
    Public Class RegistroMetricasVentasWSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        ''' <remarks/>
        Public Sub New()
            Me.Url = "http://limdeseaiv28.tim.com.pe:8909/RegistroMetricaVentaWS/RegistroMetricasVentas" + "PortSB11"
        End Sub

        ''' <remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.eai.ai.claro.com.pe/registrarMetricaVentas/registrarMetricaVentas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)> _
        Public Sub registrarMetricaVentas(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="")> ByVal registrarMetricaVentasRequest As registrarMetricaVentasRequest)
            Me.Invoke("registrarMetricaVentas", New Object() {registrarMetricaVentasRequest})
        End Sub

        ''' <remarks/>
        Public Function BeginregistrarMetricaVentas(ByVal registrarMetricaVentasRequest As registrarMetricaVentasRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("registrarMetricaVentas", New Object() {registrarMetricaVentasRequest}, callback, asyncState)
        End Function

        ''' <remarks/>
        Public Sub EndregistrarMetricaVentas(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
    End Class

    ''' <remarks/>
    Public Class registrarMetricaVentasRequest

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public audit As auditRequest

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public idMetrica As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public datosMetrica As ventaComplexType
    End Class

    ''' <remarks/>
    Public Class auditRequest

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public idTransaccion As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public ipAplicacion As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public aplicacion As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public usrAplicacion As String
    End Class

    ''' <remarks/>
    Public Class RequestOpcionalDetalleComplexType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public clave As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public valor As String
    End Class

    ''' <remarks/>
    Public Class RequestOpcionalCabeceraComplexType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public clave As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public valor As String
    End Class

    ''' <remarks/>
    Public Class ListaRequestMetrica

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("RequestOpcinalCabecera", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public RequestOpcinalCabecera As RequestOpcionalCabeceraComplexType()

        ''' <remarks/>
		<System.Xml.Serialization.XmlArrayAttribute(Form := System.Xml.Schema.XmlSchemaForm.Unqualified), _
		System.Xml.Serialization.XmlArrayItemAttribute("RequestOpcionalDetalle", GetType(RequestOpcionalDetalleComplexType), Form := System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable := False)> _
                Public detalle As RequestOpcionalDetalleComplexType()
    End Class

    ''' <remarks/>
    Public Class ventaComplexType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public cuerpoMetrica As New ListaRequestMetrica
    End Class
End Namespace