'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
'
Namespace AlertaNotificacionWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ebsAlertaNotificacionPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ebs/ws/notificacion/AlertaNotificacion/")>  _
    Public Class ebsAlertaNotificacionService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiocsv02.tim.com.pe:8909/AlertaNotificacion/ebsAlertaNotificacionSB"& _ 
"11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/notificacion/AlertaNotificacion/alertaNotificacion"& _ 
"", RequestElementName:="alertaNotificacionRequest", RequestNamespace:="http://claro.com.pe/eai/ebs/ws/notificacion/AlertaNotificacion/", ResponseNamespace:="http://claro.com.pe/eai/ebs/ws/notificacion/AlertaNotificacion/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function alertaNotificacion(ByVal audit As audiTypeRequest, ByVal tipoDoc As String, ByVal nroDoc As String, ByVal codMensaje As String, ByVal tipoProducto As String, ByVal descProducto As String, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String) As <System.Xml.Serialization.XmlElementAttribute("idTransaccion")> String
            Dim results() As Object = Me.Invoke("alertaNotificacion", New Object() {audit, tipoDoc, nroDoc, codMensaje, tipoProducto, descProducto})
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginalertaNotificacion(ByVal audit As audiTypeRequest, ByVal tipoDoc As String, ByVal nroDoc As String, ByVal codMensaje As String, ByVal tipoProducto As String, ByVal descProducto As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("alertaNotificacion", New Object() {audit, tipoDoc, nroDoc, codMensaje, tipoProducto, descProducto}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndalertaNotificacion(ByVal asyncResult As System.IAsyncResult, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/notificacion/AlertaNotificacion/alertaNotificacion"& _ 
"", RequestElementName:="AlertaNotificacionPorRenovacionRequest", RequestNamespace:="http://claro.com.pe/eai/ebs/ws/notificacion/AlertaNotificacion/", ResponseNamespace:="http://claro.com.pe/eai/ebs/ws/notificacion/AlertaNotificacion/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlertaNotificacionPorRenovacion(ByVal audit As audiTypeRequest, ByVal tipoDoc As String, ByVal nroDoc As String, ByVal Msisdn As String, ByVal EquipoComprado As String, ByVal EquipoPrecio As String, ByVal TiempoContrato As String, ByVal idCaso As String, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String) As <System.Xml.Serialization.XmlElementAttribute("idTransaccion")> String
            Dim results() As Object = Me.Invoke("AlertaNotificacionPorRenovacion", New Object() {audit, tipoDoc, nroDoc, Msisdn, EquipoComprado, EquipoPrecio, TiempoContrato, idCaso})
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginAlertaNotificacionPorRenovacion(ByVal audit As audiTypeRequest, ByVal tipoDoc As String, ByVal nroDoc As String, ByVal Msisdn As String, ByVal EquipoComprado As String, ByVal EquipoPrecio As String, ByVal TiempoContrato As String, ByVal idCaso As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AlertaNotificacionPorRenovacion", New Object() {audit, tipoDoc, nroDoc, Msisdn, EquipoComprado, EquipoPrecio, TiempoContrato, idCaso}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAlertaNotificacionPorRenovacion(ByVal asyncResult As System.IAsyncResult, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/notificacion/AlertaNotificacion/")>  _
    Public Class audiTypeRequest
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public nombreAplicacion As String
        
        '<remarks/>
        Public usuario As String
    End Class
End Namespace
