
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 08/09/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Cajas
{

  public class ZPV_REMESATable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZPV_REMESA));
    }
 
    public override object CreateNewRow()
    { 
        return new ZPV_REMESA();
    }
     
    public ZPV_REMESA this[int index] 
    {
        get 
        {
            return ((ZPV_REMESA)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZPV_REMESA value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZPV_REMESA value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZPV_REMESA value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZPV_REMESA value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZPV_REMESA value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZPV_REMESA[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
