'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace WSConsultaIGV
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ConsultaIGVWSPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ws/consultaigv/consultaigvws")>  _
    Public Class ConsultaIGVWSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://172.19.74.189:8901/ConsultIGVSBP/proxy_services/ConsultIGV"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/consultaigv/consultaigvws/consultarIGV", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function consultarIGV(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types")> ByVal consultarIGVRequest As consultarIGVRequest) As <System.Xml.Serialization.XmlElementAttribute("consultarIGVResponse", [Namespace]:="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types")> consultarIGVResponse
            Dim results() As Object = Me.Invoke("consultarIGV", New Object() {consultarIGVRequest})
            Return CType(results(0),consultarIGVResponse)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarIGV(ByVal consultarIGVRequest As consultarIGVRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarIGV", New Object() {consultarIGVRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarIGV(ByVal asyncResult As System.IAsyncResult) As consultarIGVResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),consultarIGVResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types")>  _
    Public Class consultarIGVRequest
        
        '<remarks/>
        Public auditoria As AuditRequestType

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
        Public updateCache As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class AuditRequestType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public nombreAplicacion As String
        
        '<remarks/>
        Public usuarioAplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class DefaultServiceResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public categoria As String
        
        '<remarks/>
        Public idRespuesta As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public excepcion As String
        
        '<remarks/>
        Public idTransaccion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types")>  _
    Public Class ListaIGVSResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public imputId As String
        
        '<remarks/>
        Public impuvDes As String
        
        '<remarks/>
        Public igv As Double
        
        '<remarks/>
        Public igvD As Double
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public impunTipDoc As String
        
        '<remarks/>
        Public impudFecRegistro As String
        
        '<remarks/>
        Public impudFecIniVigencia As String
        
        '<remarks/>
        Public impudFecFinVigencia As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types")>  _
    Public Class consultarIGVResponse
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listaIGVS")>  _
        Public listaIGVS() As ListaIGVSResponseType
        
        '<remarks/>
        Public defaultServiceResponse As DefaultServiceResponse
    End Class
End Namespace
