'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace ProcesoPortabilidadWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BSS_ProcesoPortabilidadSOAP11Binding", [Namespace]:="http://claro.com.pe/esb/ventas/BSS_ProcesoPortabilidad/v1/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(claroFault))>  _
    Public Class BSS_ProcesoPortabilidadSOAP11BindingQSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Public headerRequest As HeaderRequestType
        
        Public headerResponse As HeaderResponseType
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://172.17.26.51:21000/BSS_ProcesoPortabilidad/SRV_ProcesoPortabilidad/Service"& _ 
"/BSS_ProcesoPortabilidad_v1"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/esb/ventas/BSS_ProcesoPortabilidad/v1/validaCPVigenciaReposit"& _ 
"orio", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function validaCPVigenciaRepositorio(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/validaCPVigenciaRe"& _ 
"positorio/")> ByVal validaCPVigenciaRepositorioRequest As validaCPVigenciaRepositorioRequest) As <System.Xml.Serialization.XmlElementAttribute("validaCPVigenciaRepositorioResponse", [Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/validaCPVigenciaRe"& _ 
"positorio/")> validaCPVigenciaRepositorioResponse
            Dim results() As Object = Me.Invoke("validaCPVigenciaRepositorio", New Object() {validaCPVigenciaRepositorioRequest})
            Return CType(results(0),validaCPVigenciaRepositorioResponse)
        End Function
        
        '<remarks/>
        Public Function BeginvalidaCPVigenciaRepositorio(ByVal validaCPVigenciaRepositorioRequest As validaCPVigenciaRepositorioRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("validaCPVigenciaRepositorio", New Object() {validaCPVigenciaRepositorioRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndvalidaCPVigenciaRepositorio(ByVal asyncResult As System.IAsyncResult) As validaCPVigenciaRepositorioResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),validaCPVigenciaRepositorioResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/esb/ventas/BSS_ProcesoPortabilidad/v1/obtenerEstadoCP", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function obtenerEstadoCP(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/obtenerEstadoCP/")> ByVal obtenerEstadoCPRequest As obtenerEstadoCPRequest) As <System.Xml.Serialization.XmlElementAttribute("obtenerEstadoCPResponse", [Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/obtenerEstadoCP/")> obtenerEstadoCPResponse
            Dim results() As Object = Me.Invoke("obtenerEstadoCP", New Object() {obtenerEstadoCPRequest})
            Return CType(results(0),obtenerEstadoCPResponse)
        End Function
        
        '<remarks/>
        Public Function BeginobtenerEstadoCP(ByVal obtenerEstadoCPRequest As obtenerEstadoCPRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtenerEstadoCP", New Object() {obtenerEstadoCPRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtenerEstadoCP(ByVal asyncResult As System.IAsyncResult) As obtenerEstadoCPResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),obtenerEstadoCPResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/esb/ventas/BSS_ProcesoPortabilidad/v1/realizarProgramacion", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function realizarProgramacion(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/realizarProgramaci"& _ 
"on/")> ByVal realizarProgramacionRequest As realizarProgramacionRequest) As <System.Xml.Serialization.XmlElementAttribute("realizarProgramacionResponse", [Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/realizarProgramaci"& _ 
"on/")> realizarProgramacionResponse
            Dim results() As Object = Me.Invoke("realizarProgramacion", New Object() {realizarProgramacionRequest})
            Return CType(results(0),realizarProgramacionResponse)
        End Function
        
        '<remarks/>
        Public Function BeginrealizarProgramacion(ByVal realizarProgramacionRequest As realizarProgramacionRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("realizarProgramacion", New Object() {realizarProgramacionRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndrealizarProgramacion(ByVal asyncResult As System.IAsyncResult) As realizarProgramacionResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),realizarProgramacionResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/esb/ventas/BSS_ProcesoPortabilidad/v1/comprobarDeuda", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function comprobarDeuda(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/comprobarDeuda/")> ByVal comprobarDeudaRequest As comprobarDeudaRequest) As <System.Xml.Serialization.XmlElementAttribute("comprobarDeudaResponse", [Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/comprobarDeuda/")> comprobarDeudaResponse
            Dim results() As Object = Me.Invoke("comprobarDeuda", New Object() {comprobarDeudaRequest})
            Return CType(results(0),comprobarDeudaResponse)
        End Function
        
        '<remarks/>
        Public Function BegincomprobarDeuda(ByVal comprobarDeudaRequest As comprobarDeudaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("comprobarDeuda", New Object() {comprobarDeudaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcomprobarDeuda(ByVal asyncResult As System.IAsyncResult) As comprobarDeudaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),comprobarDeudaResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/"),  _
     System.Xml.Serialization.XmlRootAttribute("headerRequest", [Namespace]:="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/", IsNullable:=false)>  _
    Public Class HeaderRequestType
        Inherits System.Web.Services.Protocols.SoapHeader
        
        '<remarks/>
        Public canal As String
        
        '<remarks/>
        Public idAplicacion As String
        
        '<remarks/>
        Public usuarioAplicacion As String
        
        '<remarks/>
        Public usuarioSesion As String
        
        '<remarks/>
        Public idTransaccionESB As String
        
        '<remarks/>
        Public idTransaccionNegocio As String
        
        '<remarks/>
        Public fechaInicio As Date
        
        '<remarks/>
        Public nodoAdicional As Object
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/generico/claroFault/v1/")>  _
    Public Class claroFault
        
        '<remarks/>
        Public idAutoria As String
        
        '<remarks/>
        Public codigoError As String
        
        '<remarks/>
        Public descripcionError As String
        
        '<remarks/>
        Public ubicacionError As String
        
        '<remarks/>
        Public fecha As Date
        
        '<remarks/>
        Public errorOrigen As Object
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/comprobarDeuda/")>  _
    Public Class comprobarDeudaResponse
        
        '<remarks/>
        Public responseStatus As ResponseStatus
        
        '<remarks/>
        Public responseData As ResponseData3
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", [Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable:=false)>  _
        Public listaResponseOpcional() As ResponseOpcionalTypeResponseOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/generico/responseStatus/v1/")>  _
    Public Class ResponseStatus
        
        '<remarks/>
        Public estado As Integer
        
        '<remarks/>
        Public codigoRespuesta As String
        
        '<remarks/>
        Public descripcionRespuesta As String
        
        '<remarks/>
        Public ubicacionError As String
        
        '<remarks/>
        Public fecha As Date
        
        '<remarks/>
        Public origen As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute(TypeName:="ResponseData", [Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/comprobarDeuda/")>  _
    Public Class ResponseData3
        
        '<remarks/>
        Public solinCodigo As String
        
        '<remarks/>
        Public deuda As String
        
        '<remarks/>
        Public moneda As String
        
        '<remarks/>
        Public numLinea As String
        
        '<remarks/>
        Public fechVencFactura As String
        
        '<remarks/>
        Public numSecuencial As String
        
        '<remarks/>
        Public flagEnvioCp As String
        
        '<remarks/>
        Public flagEnvioSp As String
        
        '<remarks/>
        Public tipoProducto As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/")>  _
    Public Class ResponseOpcionalTypeResponseOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public campo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/comprobarDeuda/")>  _
    Public Class comprobarDeudaRequest
        
        '<remarks/>
        Public solinCodigo As String
        
        '<remarks/>
        Public numLinea As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", [Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable:=false)>  _
        Public listaResquestOpcional() As RequestOpcionalTypeRequestOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/")>  _
    Public Class RequestOpcionalTypeRequestOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public campo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/realizarProgramaci"& _ 
"on/")>  _
    Public Class realizarProgramacionRequest
        
        '<remarks/>
        Public idSolicitud As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", [Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable:=false)>  _
        Public listaResquestOpcional() As RequestOpcionalTypeRequestOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/realizarProgramaci"& _ 
"on/")>  _
    Public Class realizarProgramacionResponse
        
        '<remarks/>
        Public responseStatus As ResponseStatus
        
        '<remarks/>
        Public responseData As ResponseData2
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", [Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable:=false)>  _
        Public listaResponseOpcional() As ResponseOpcionalTypeResponseOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute(TypeName:="ResponseData", [Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/realizarProgramaci"& _ 
"on/")>  _
    Public Class ResponseData2
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Cursor", IsNullable:=false)>  _
        Public cursorDet() As CursorDetTypeCursor1
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute(TypeName:="CursorDetTypeCursor", [Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/realizarProgramaci"& _ 
"on/")>  _
    Public Class CursorDetTypeCursor1
        
        '<remarks/>
        Public idMensaje As String
        
        '<remarks/>
        Public fechCreacion As String
        
        '<remarks/>
        Public idSolicitud As String
        
        '<remarks/>
        Public linea As String
        
        '<remarks/>
        Public fechProgramacion As String
        
        '<remarks/>
        Public remitente As String
        
        '<remarks/>
        Public destinatario As String
        
        '<remarks/>
        Public tipoPorta As String
        
        '<remarks/>
        Public tipoProducto As String
        
        '<remarks/>
        Public tipoServicio As String
        
        '<remarks/>
        Public tipoPlan As String
        
        '<remarks/>
        Public usuCrea As String
        
        '<remarks/>
        Public fechProgramacionXml As String
        
        '<remarks/>
        Public solPorta As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/obtenerEstadoCP/")>  _
    Public Class obtenerEstadoCPRequest
        
        '<remarks/>
        Public nroSecuencial As String
        
        '<remarks/>
        Public codSolicitud As String
        
        '<remarks/>
        Public inicioRango As String
        
        '<remarks/>
        Public flagConsulta As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", [Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable:=false)>  _
        Public listaResquestOpcional() As RequestOpcionalTypeRequestOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/obtenerEstadoCP/")>  _
    Public Class CursorDetTypeCursor
        
        '<remarks/>
        Public idSolicitud As String
        
        '<remarks/>
        Public codSolicitud As String
        
        '<remarks/>
        Public inicioRango As String
        
        '<remarks/>
        Public fechActivacion As String
        
        '<remarks/>
        Public envioCp As String
        
        '<remarks/>
        Public flagEnvio As String
        
        '<remarks/>
        Public estadoProcesoCp As String
        
        '<remarks/>
        Public estadoCp As String
        
        '<remarks/>
        Public motivoCp As String
        
        '<remarks/>
        Public descripMotivo As String
        
        '<remarks/>
        Public deudaCedente As String
        
        '<remarks/>
        Public numIntentos As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute(TypeName:="ResponseData", [Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/obtenerEstadoCP/")>  _
    Public Class ResponseData1
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Cursor", IsNullable:=false)>  _
        Public cursorDet() As CursorDetTypeCursor
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/obtenerEstadoCP/")>  _
    Public Class obtenerEstadoCPResponse
        
        '<remarks/>
        Public responseStatus As ResponseStatus
        
        '<remarks/>
        Public responseData As ResponseData1
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", [Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable:=false)>  _
        Public listaResponseOpcional() As ResponseOpcionalTypeResponseOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/validaCPVigenciaRe"& _ 
"positorio/")>  _
    Public Class validaCPVigenciaRepositorioRequest
        
        '<remarks/>
        Public codCedente As String
        
        '<remarks/>
        Public modalidad As String
        
        '<remarks/>
        Public inicioRango As String
        
        '<remarks/>
        Public tipoDocumento As String
        
        '<remarks/>
        Public nroDocumento As String
        
        '<remarks/>
        Public usuAplic As String
        
        '<remarks/>
        Public codSolicitud As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", [Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable:=false)>  _
        Public listaResquestOpcional() As RequestOpcionalTypeRequestOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/validaCPVigenciaRe"& _ 
"positorio/")>  _
    Public Class validaCPVigenciaRepositorioResponse
        
        '<remarks/>
        Public responseStatus As ResponseStatus
        
        '<remarks/>
        Public responseData As ResponseData
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", [Namespace]:="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable:=false)>  _
        Public listaResponseOpcional() As ResponseOpcionalTypeResponseOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/ventas/procesoPortabilidad/sec/v1/validaCPVigenciaRe"& _ 
"positorio/")>  _
    Public Class ResponseData
        
        '<remarks/>
        Public codSolicitud As String
        
        '<remarks/>
        Public idSolicitud As String
        
        '<remarks/>
        Public numSecuencial As String
        
        '<remarks/>
        Public numMensajes As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/"),  _
     System.Xml.Serialization.XmlRootAttribute("headerResponse", [Namespace]:="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/", IsNullable:=false)>  _
    Public Class HeaderResponseType
        Inherits System.Web.Services.Protocols.SoapHeader
        
        '<remarks/>
        Public idTransaccionESB As String
        
        '<remarks/>
        Public idTransaccionNegocio As String
        
        '<remarks/>
        Public fechaInicio As Date
        
        '<remarks/>
        Public fechaFin As Date
        
        '<remarks/>
        Public nodoAdicional As Object
    End Class
End Namespace
