'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
'
Namespace CuentasClienteWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ObtieneCuentasClienteServiceSoapBinding", [Namespace]:="http://pe/com/claro/esb/services/activacionespostpago/ws")>  _
    Public Class ObtieneCuentasClienteService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv06.tim.com.pe:8909/ActivacionesPostpagoProcess/ObtieneCuentasCli"& _ 
"ente"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/activacionespostpago/ws", ResponseNamespace:="http://pe/com/claro/esb/services/activacionespostpago/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtieneCuentasCliente(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")> ByVal callservice As callservice) As <System.Xml.Serialization.XmlElementAttribute("DATOS.LISTA.CUENTA", [Namespace]:="wli/activaciones/datosListaCuentas")> DATOSLISTACUENTA
            Dim results() As Object = Me.Invoke("obtieneCuentasCliente", New Object() {callservice})
            Return CType(results(0),DATOSLISTACUENTA)
        End Function
        
        '<remarks/>
        Public Function BeginobtieneCuentasCliente(ByVal callservice As callservice, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtieneCuentasCliente", New Object() {callservice}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtieneCuentasCliente(ByVal asyncResult As System.IAsyncResult) As DATOSLISTACUENTA
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),DATOSLISTACUENTA)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callservice
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public header As callserviceHeader
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public datos As callserviceDatos
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceHeader
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public cliente As callserviceHeaderCliente
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public servicio As callserviceHeaderServicio
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceHeaderCliente
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public servicio As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>  _
        Public timeout As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public clave As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public aplicacion As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public timestamp As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idsrv As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("filterClass", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public filterClass() As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="wli/activaciones/datosListaCuentas")>  _
    Public Class lineaType
        
        '<remarks/>
        Public NUM_TELEFONO As String
        
        '<remarks/>
        Public PLAN As String
        
        '<remarks/>
        Public FECHA_ACTIVAC As String
        
        '<remarks/>
        Public ESTADO_LINEA As String
        
        '<remarks/>
        Public FECHA_CAMB_ESTADO As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="wli/activaciones/datosListaCuentas")>  _
    Public Class DATOSLISTACUENTACUENTA
        
        '<remarks/>
        Public CS_ID As String
        
        '<remarks/>
        Public CODIGO_BSCS As String
        
        '<remarks/>
        Public CS_LEVEL_CODE As String
        
        '<remarks/>
        Public CS_ID_HIGH As String
        
        '<remarks/>
        Public CODIGO_BSCS_HIGH As String
        
        '<remarks/>
        Public NOMBRE_TITULAR As String
        
        '<remarks/>
        Public DIRECCION_DESCRIPCION As String
        
        '<remarks/>
        Public REFERENCIA As String
        
        '<remarks/>
        Public DESC_DPTO As String
        
        '<remarks/>
        Public DESC_PROV As String
        
        '<remarks/>
        Public DESC_DIST As String
        
        '<remarks/>
        Public COD_UBIGEO As String
        
        '<remarks/>
        Public LIM_CREDITO As String
        
        '<remarks/>
        Public ESTADO_CUENTA As String
        
        '<remarks/>
        Public RESPONS_PAGO As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("linea")>  _
        Public linea() As lineaType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="wli/activaciones/datosListaCuentas")>  _
    Public Class DATOSLISTACUENTARESPUESTA
        
        '<remarks/>
        Public TRANSACC_ID As String
        
        '<remarks/>
        Public FLAG_PROCESO As String
        
        '<remarks/>
        Public MENSAJE_PVU As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="wli/activaciones/datosListaCuentas")>  _
    Public Class DATOSLISTACUENTA
        
        '<remarks/>
        Public RESPUESTA As DATOSLISTACUENTARESPUESTA
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CUENTA")>  _
        Public CUENTA() As DATOSLISTACUENTACUENTA
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceDatosTablaFilaParametro
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public nombre As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public modo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceDatosTabla
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), _
         System.Xml.Serialization.XmlArrayItemAttribute("parametro", GetType(callserviceDatosTablaFilaParametro), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=False)> _
        Public fila() As callserviceDatosTablaFilaParametro
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public nombre As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceDatosParametro
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public nombre As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public modo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceDatos
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametro", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public parametro() As callserviceDatosParametro
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("tabla", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public tabla() As callserviceDatosTabla
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceHeaderServicioRetcode
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public modo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As System.SByte
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public valorSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://temp.openuri.org/ocs/callService")>  _
    Public Class callserviceHeaderServicio
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public retcode As callserviceHeaderServicioRetcode
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public errdesc As String
    End Class
End Namespace
