'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace CambioSimWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ebsCambioSimPrepagoPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CambioSimPrepago")>  _
    Public Class ebsCambioSimPrepagoService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv13.tim.com.pe:7909/CambioSimPrepago/ebsCambioSimPrepagoSB11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/postventa/CambioSimPrepago/ejecutarCambioSim", RequestElementName:="ejecutarCambioSimRequest", RequestNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CambioSimPrepago", ResponseNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CambioSimPrepago", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ejecutarCambioSim(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal usuarioApp As String, ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal msisdn As String, ByVal iccidNuevo As String, ByVal codigoBloqueo As String, ByVal canalAtencion As String, ByVal tipoBloqueo As String, ByRef mensajeRespuesta As String) As <System.Xml.Serialization.XmlElementAttribute("codigoRespuesta")> String
            Dim results() As Object = Me.Invoke("ejecutarCambioSim", New Object() {idTransaccion, ipAplicacion, usuarioApp, tipoDocumento, numeroDocumento, msisdn, iccidNuevo, codigoBloqueo, canalAtencion, tipoBloqueo})
            idTransaccion = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginejecutarCambioSim(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal usuarioApp As String, ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal msisdn As String, ByVal iccidNuevo As String, ByVal codigoBloqueo As String, ByVal canalAtencion As String, ByVal tipoBloqueo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarCambioSim", New Object() {idTransaccion, ipAplicacion, usuarioApp, tipoDocumento, numeroDocumento, msisdn, iccidNuevo, codigoBloqueo, canalAtencion, tipoBloqueo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndejecutarCambioSim(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeRespuesta As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
