'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
'
Namespace ESBTransaccionesWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ebsTransaccionesServiceSoapBinding", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws")>  _
    Public Class ebsTransaccionesService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv03.tim.com.pe:8909/TransaccionesWS/ebsTransacciones"
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", ResponseNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ejecutarRecargasBolsas(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/recargas/schemas/Recargas.xsd")> ByVal RecargasRequest As RecargasRequest) As <System.Xml.Serialization.XmlElementAttribute("RecargasResponse", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/recargas/schemas/Recargas.xsd")> RecargasResponse
            Dim results() As Object = Me.Invoke("ejecutarRecargasBolsas", New Object() {RecargasRequest})
            Return CType(results(0), RecargasResponse)
        End Function

        '<remarks/>
        Public Function BeginejecutarRecargasBolsas(ByVal RecargasRequest As RecargasRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarRecargasBolsas", New Object() {RecargasRequest}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndejecutarRecargasBolsas(ByVal asyncResult As System.IAsyncResult) As RecargasResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), RecargasResponse)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", ResponseNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ejecutarPromocion(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/promociones/schemas/Promociones.xsd")> ByVal PromocionRequest As PromocionRequest) As <System.Xml.Serialization.XmlElementAttribute("PromocionResponse", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/promociones/schemas/Promociones.xsd")> PromocionResponse
            Dim results() As Object = Me.Invoke("ejecutarPromocion", New Object() {PromocionRequest})
            Return CType(results(0), PromocionResponse)
        End Function

        '<remarks/>
        Public Function BeginejecutarPromocion(ByVal PromocionRequest As PromocionRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarPromocion", New Object() {PromocionRequest}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndejecutarPromocion(ByVal asyncResult As System.IAsyncResult) As PromocionResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), PromocionResponse)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", ResponseNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ejecutarBloqueoDesbloqueo(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/bloqueos/schemas/BloqueoDesbloqueo.xs" & _
"d")> ByVal BloqueoDesbloqueoRequest As BloqueoDesbloqueoRequest) As <System.Xml.Serialization.XmlElementAttribute("BloqueoDesbloqueoResponse", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/bloqueos/schemas/BloqueoDesbloqueo.xs" & _
"d")> BloqueoDesbloqueoResponse
            Dim results() As Object = Me.Invoke("ejecutarBloqueoDesbloqueo", New Object() {BloqueoDesbloqueoRequest})
            Return CType(results(0), BloqueoDesbloqueoResponse)
        End Function

        '<remarks/>
        Public Function BeginejecutarBloqueoDesbloqueo(ByVal BloqueoDesbloqueoRequest As BloqueoDesbloqueoRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarBloqueoDesbloqueo", New Object() {BloqueoDesbloqueoRequest}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndejecutarBloqueoDesbloqueo(ByVal asyncResult As System.IAsyncResult) As BloqueoDesbloqueoResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), BloqueoDesbloqueoResponse)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", ResponseNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function resetearIntentos(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/recargas/schemas/Recargas.xsd")> ByVal RecargasIntentosRequest As RecargasIntentosRequest) As <System.Xml.Serialization.XmlElementAttribute("RecargasResponse", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/recargas/schemas/Recargas.xsd")> RecargasResponse
            Dim results() As Object = Me.Invoke("resetearIntentos", New Object() {RecargasIntentosRequest})
            Return CType(results(0), RecargasResponse)
        End Function

        '<remarks/>
        Public Function BeginresetearIntentos(ByVal RecargasIntentosRequest As RecargasIntentosRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("resetearIntentos", New Object() {RecargasIntentosRequest}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndresetearIntentos(ByVal asyncResult As System.IAsyncResult) As RecargasResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), RecargasResponse)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", ResponseNamespace:="http://pe/com/claro/esb/services/prepago/in/transacciones/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ejecutarCambioChip(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/cambiochip/schemas/CambioChip.xsd")> ByVal CambioChipRequest As CambioChipRequest) As <System.Xml.Serialization.XmlElementAttribute("CambioChipResponse", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/cambiochip/schemas/CambioChip.xsd")> CambioChipResponse
            Dim results() As Object = Me.Invoke("ejecutarCambioChip", New Object() {CambioChipRequest})
            Return CType(results(0), CambioChipResponse)
        End Function

        '<remarks/>
        Public Function BeginejecutarCambioChip(ByVal CambioChipRequest As CambioChipRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarCambioChip", New Object() {CambioChipRequest}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndejecutarCambioChip(ByVal asyncResult As System.IAsyncResult) As CambioChipResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), CambioChipResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/recargas/schemas/Recargas.xsd")>  _
    Public Class RecargasRequest
        
        '<remarks/>
        Public telefono As String
        
        '<remarks/>
        Public bolsa As String
        
        '<remarks/>
        Public monto As String
        
        '<remarks/>
        Public dias As String
        
        '<remarks/>
        Public accion As String
        
        '<remarks/>
        Public id As String
        
        '<remarks/>
        Public usuario As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/cambiochip/schemas/CambioChip.xsd")>  _
    Public Class CambioChipResponse
        
        '<remarks/>
        Public resultado As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public transaccion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/cambiochip/schemas/CambioChip.xsd")>  _
    Public Class CambioChipRequest
        
        '<remarks/>
        Public msisdn As String
        
        '<remarks/>
        Public iccidNuevo As String
        
        '<remarks/>
        Public id As String
        
        '<remarks/>
        Public ip As String
        
        '<remarks/>
        Public empleado As String
        
        '<remarks/>
        Public aplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/recargas/schemas/Recargas.xsd")>  _
    Public Class RecargasIntentosRequest
        
        '<remarks/>
        Public telefono As String
        
        '<remarks/>
        Public intentos As String
        
        '<remarks/>
        Public id As String
        
        '<remarks/>
        Public usuario As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/bloqueos/schemas/BloqueoDesbloqueo.xs"& _ 
"d")>  _
    Public Class BloqueoDesbloqueoResponse
        
        '<remarks/>
        Public resultado As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public transaccion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/bloqueos/schemas/BloqueoDesbloqueo.xs"& _ 
"d")>  _
    Public Class BloqueoDesbloqueoRequest
        
        '<remarks/>
        Public msisdn As String
        
        '<remarks/>
        Public accion As String
        
        '<remarks/>
        Public id As String
        
        '<remarks/>
        Public ip As String
        
        '<remarks/>
        Public empleado As String
        
        '<remarks/>
        Public aplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/promociones/schemas/Promociones.xsd")>  _
    Public Class PromocionResponse
        
        '<remarks/>
        Public resultado As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public transaccion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/promociones/schemas/Promociones.xsd")>  _
    Public Class PromocionRequest
        
        '<remarks/>
        Public telefono As String
        
        '<remarks/>
        Public bolsa As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/recargas/schemas/Recargas.xsd")>  _
    Public Class RecargasResponse
        
        '<remarks/>
        Public resultado As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public transaccion As String
    End Class
End Namespace
