//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2503
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
// 
namespace COM_SIC_FacturaElectronica.PaperLessWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OnlineSOAP11Binding", Namespace="http://ws.online.asp.core.paperless.cl")]
    public class Online : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Online() {
            this.Url = "http://172.19.74.198:8080/axis2/services/Online";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineRecovery", RequestNamespace="http://ws.online.asp.core.paperless.cl", ResponseNamespace="http://ws.online.asp.core.paperless.cl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string OnlineRecovery([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ruc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, int tipoDoc, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tipoDocSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string folio, int tipoRetorno, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tipoRetornoSpecified) {
            object[] results = this.Invoke("OnlineRecovery", new object[] {
                        ruc,
                        login,
                        clave,
                        tipoDoc,
                        tipoDocSpecified,
                        folio,
                        tipoRetorno,
                        tipoRetornoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOnlineRecovery(string ruc, string login, string clave, int tipoDoc, bool tipoDocSpecified, string folio, int tipoRetorno, bool tipoRetornoSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OnlineRecovery", new object[] {
                        ruc,
                        login,
                        clave,
                        tipoDoc,
                        tipoDocSpecified,
                        folio,
                        tipoRetorno,
                        tipoRetornoSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOnlineRecovery(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:CargaInformeBajas", RequestNamespace="http://ws.online.asp.core.paperless.cl", ResponseNamespace="http://ws.online.asp.core.paperless.cl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string CargaInformeBajas([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ruc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string docTxt, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string periodo) {
            object[] results = this.Invoke("CargaInformeBajas", new object[] {
                        ruc,
                        login,
                        clave,
                        docTxt,
                        periodo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCargaInformeBajas(string ruc, string login, string clave, string docTxt, string periodo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CargaInformeBajas", new object[] {
                        ruc,
                        login,
                        clave,
                        docTxt,
                        periodo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCargaInformeBajas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineARC", RequestNamespace="http://ws.online.asp.core.paperless.cl", ResponseNamespace="http://ws.online.asp.core.paperless.cl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string OnlineARC([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ruc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rucEmisor, int tipoDoc, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tipoDocSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string folio, int estado, [System.Xml.Serialization.XmlIgnoreAttribute()] bool estadoSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mensaje) {
            object[] results = this.Invoke("OnlineARC", new object[] {
                        ruc,
                        login,
                        clave,
                        rucEmisor,
                        tipoDoc,
                        tipoDocSpecified,
                        folio,
                        estado,
                        estadoSpecified,
                        mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOnlineARC(string ruc, string login, string clave, string rucEmisor, int tipoDoc, bool tipoDocSpecified, string folio, int estado, bool estadoSpecified, string mensaje, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OnlineARC", new object[] {
                        ruc,
                        login,
                        clave,
                        rucEmisor,
                        tipoDoc,
                        tipoDocSpecified,
                        folio,
                        estado,
                        estadoSpecified,
                        mensaje}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOnlineARC(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineConsultaEstado", RequestNamespace="http://ws.online.asp.core.paperless.cl", ResponseNamespace="http://ws.online.asp.core.paperless.cl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string OnlineConsultaEstado([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ruc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rucReceptor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fechaInicio, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fechaFin, int estado, [System.Xml.Serialization.XmlIgnoreAttribute()] bool estadoSpecified) {
            object[] results = this.Invoke("OnlineConsultaEstado", new object[] {
                        ruc,
                        login,
                        clave,
                        rucReceptor,
                        fechaInicio,
                        fechaFin,
                        estado,
                        estadoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOnlineConsultaEstado(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado, bool estadoSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OnlineConsultaEstado", new object[] {
                        ruc,
                        login,
                        clave,
                        rucReceptor,
                        fechaInicio,
                        fechaFin,
                        estado,
                        estadoSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOnlineConsultaEstado(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineRecoveryRecList", RequestNamespace="http://ws.online.asp.core.paperless.cl", ResponseNamespace="http://ws.online.asp.core.paperless.cl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string OnlineRecoveryRecList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ruc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fecha) {
            object[] results = this.Invoke("OnlineRecoveryRecList", new object[] {
                        ruc,
                        login,
                        clave,
                        fecha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOnlineRecoveryRecList(string ruc, string login, string clave, string fecha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OnlineRecoveryRecList", new object[] {
                        ruc,
                        login,
                        clave,
                        fecha}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOnlineRecoveryRecList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineGeneration", RequestNamespace="http://ws.online.asp.core.paperless.cl", ResponseNamespace="http://ws.online.asp.core.paperless.cl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string OnlineGeneration([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ruc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string docTxt, int tipoFoliacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tipoFoliacionSpecified, int tipoRetorno, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tipoRetornoSpecified) {
            object[] results = this.Invoke("OnlineGeneration", new object[] {
                        ruc,
                        login,
                        clave,
                        docTxt,
                        tipoFoliacion,
                        tipoFoliacionSpecified,
                        tipoRetorno,
                        tipoRetornoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOnlineGeneration(string ruc, string login, string clave, string docTxt, int tipoFoliacion, bool tipoFoliacionSpecified, int tipoRetorno, bool tipoRetornoSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OnlineGeneration", new object[] {
                        ruc,
                        login,
                        clave,
                        docTxt,
                        tipoFoliacion,
                        tipoFoliacionSpecified,
                        tipoRetorno,
                        tipoRetornoSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOnlineGeneration(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineEventos", RequestNamespace="http://ws.online.asp.core.paperless.cl", ResponseNamespace="http://ws.online.asp.core.paperless.cl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string OnlineEventos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ruc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string docTxt) {
            object[] results = this.Invoke("OnlineEventos", new object[] {
                        ruc,
                        login,
                        clave,
                        docTxt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOnlineEventos(string ruc, string login, string clave, string docTxt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OnlineEventos", new object[] {
                        ruc,
                        login,
                        clave,
                        docTxt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOnlineEventos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:main", RequestNamespace="http://ws.online.asp.core.paperless.cl", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void main([System.Xml.Serialization.XmlElementAttribute("args", IsNullable=true)] string[] args) {
            this.Invoke("main", new object[] {
                        args});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginmain(string[] args, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("main", new object[] {
                        args}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endmain(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineRecoveryRec", RequestNamespace="http://ws.online.asp.core.paperless.cl", ResponseNamespace="http://ws.online.asp.core.paperless.cl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string OnlineRecoveryRec([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ruc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rucEmisor, int tipoDoc, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tipoDocSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string folio, int tipoRetorno, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tipoRetornoSpecified) {
            object[] results = this.Invoke("OnlineRecoveryRec", new object[] {
                        ruc,
                        login,
                        clave,
                        rucEmisor,
                        tipoDoc,
                        tipoDocSpecified,
                        folio,
                        tipoRetorno,
                        tipoRetornoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOnlineRecoveryRec(string ruc, string login, string clave, string rucEmisor, int tipoDoc, bool tipoDocSpecified, string folio, int tipoRetorno, bool tipoRetornoSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OnlineRecoveryRec", new object[] {
                        ruc,
                        login,
                        clave,
                        rucEmisor,
                        tipoDoc,
                        tipoDocSpecified,
                        folio,
                        tipoRetorno,
                        tipoRetornoSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOnlineRecoveryRec(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
