
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 20/07/2015
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  [RfcStructure(AbapName ="TLINE" , Length = 134)]
  public class TLINE : SAPStructure
  {
    
    [RfcField(AbapName = "TDFORMAT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 0)]
    [XmlElement("TDFORMAT")]
    public string Tdformat
    { 
       get
       {
          return _Tdformat;
       }
       set
       {
          _Tdformat = value;
       }
    }
    private string _Tdformat;

    [RfcField(AbapName = "TDLINE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 132, Offset = 2)]
    [XmlElement("TDLINE")]
    public string Tdline
    { 
       get
       {
          return _Tdline;
       }
       set
       {
          _Tdline = value;
       }
    }
    private string _Tdline;

  }

}
