
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 20/07/2015
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  public class ZFE_CABECERATable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZFE_CABECERA));
    }
 
    public override object CreateNewRow()
    { 
        return new ZFE_CABECERA();
    }
     
    public ZFE_CABECERA this[int index] 
    {
        get 
        {
            return ((ZFE_CABECERA)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZFE_CABECERA value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZFE_CABECERA value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZFE_CABECERA value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZFE_CABECERA value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZFE_CABECERA value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZFE_CABECERA[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
