
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 20/07/2015
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  [RfcStructure(AbapName ="ZFE_CABECERA_N" , Length = 1081)]
  public class ZFE_CABECERA_N : SAPStructure
  {
    
    [RfcField(AbapName = "FECHA_EMISION", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 0)]
    [XmlElement("FECHA_EMISION")]
    public string Fecha_Emision
    { 
       get
       {
          return _Fecha_Emision;
       }
       set
       {
          _Fecha_Emision = value;
       }
    }
    private string _Fecha_Emision;

    [RfcField(AbapName = "APE_RAZON_SOCIAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Offset = 8)]
    [XmlElement("APE_RAZON_SOCIAL")]
    public string Ape_Razon_Social
    { 
       get
       {
          return _Ape_Razon_Social;
       }
       set
       {
          _Ape_Razon_Social = value;
       }
    }
    private string _Ape_Razon_Social;

    [RfcField(AbapName = "NOMBRE_COMERCIAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Offset = 38)]
    [XmlElement("NOMBRE_COMERCIAL")]
    public string Nombre_Comercial
    { 
       get
       {
          return _Nombre_Comercial;
       }
       set
       {
          _Nombre_Comercial = value;
       }
    }
    private string _Nombre_Comercial;

    [RfcField(AbapName = "DOMICILIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 100, Offset = 68)]
    [XmlElement("DOMICILIO")]
    public string Domicilio
    { 
       get
       {
          return _Domicilio;
       }
       set
       {
          _Domicilio = value;
       }
    }
    private string _Domicilio;

    [RfcField(AbapName = "RUC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 168)]
    [XmlElement("RUC")]
    public string Ruc
    { 
       get
       {
          return _Ruc;
       }
       set
       {
          _Ruc = value;
       }
    }
    private string _Ruc;

    [RfcField(AbapName = "TIPODOC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 184)]
    [XmlElement("TIPODOC")]
    public string Tipodoc
    { 
       get
       {
          return _Tipodoc;
       }
       set
       {
          _Tipodoc = value;
       }
    }
    private string _Tipodoc;

    [RfcField(AbapName = "NUMERACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Offset = 186)]
    [XmlElement("NUMERACION")]
    public string Numeracion
    { 
       get
       {
          return _Numeracion;
       }
       set
       {
          _Numeracion = value;
       }
    }
    private string _Numeracion;

    [RfcField(AbapName = "TIPO_DOCID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 199)]
    [XmlElement("TIPO_DOCID")]
    public string Tipo_Docid
    { 
       get
       {
          return _Tipo_Docid;
       }
       set
       {
          _Tipo_Docid = value;
       }
    }
    private string _Tipo_Docid;

    [RfcField(AbapName = "DOCID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 201)]
    [XmlElement("DOCID")]
    public string Docid
    { 
       get
       {
          return _Docid;
       }
       set
       {
          _Docid = value;
       }
    }
    private string _Docid;

    [RfcField(AbapName = "NOMBRE_ADQUI", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 100, Offset = 217)]
    [XmlElement("NOMBRE_ADQUI")]
    public string Nombre_Adqui
    { 
       get
       {
          return _Nombre_Adqui;
       }
       set
       {
          _Nombre_Adqui = value;
       }
    }
    private string _Nombre_Adqui;

    [RfcField(AbapName = "T_VN_AFECTAS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 317)]
    [XmlElement("T_VN_AFECTAS")]
    public Decimal T_Vn_Afectas
    { 
       get
       {
          return _T_Vn_Afectas;
       }
       set
       {
          _T_Vn_Afectas = value;
       }
    }
    private Decimal _T_Vn_Afectas;

    [RfcField(AbapName = "T_VN_INAFECT", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 325)]
    [XmlElement("T_VN_INAFECT")]
    public Decimal T_Vn_Inafect
    { 
       get
       {
          return _T_Vn_Inafect;
       }
       set
       {
          _T_Vn_Inafect = value;
       }
    }
    private Decimal _T_Vn_Inafect;

    [RfcField(AbapName = "T_VN_EXONERA", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 333)]
    [XmlElement("T_VN_EXONERA")]
    public Decimal T_Vn_Exonera
    { 
       get
       {
          return _T_Vn_Exonera;
       }
       set
       {
          _T_Vn_Exonera = value;
       }
    }
    private Decimal _T_Vn_Exonera;

    [RfcField(AbapName = "T_VN_GRATUITAS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 341)]
    [XmlElement("T_VN_GRATUITAS")]
    public Decimal T_Vn_Gratuitas
    { 
       get
       {
          return _T_Vn_Gratuitas;
       }
       set
       {
          _T_Vn_Gratuitas = value;
       }
    }
    private Decimal _T_Vn_Gratuitas;

    [RfcField(AbapName = "S_IGV", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 349)]
    [XmlElement("S_IGV")]
    public Decimal S_Igv
    { 
       get
       {
          return _S_Igv;
       }
       set
       {
          _S_Igv = value;
       }
    }
    private Decimal _S_Igv;

    [RfcField(AbapName = "S_ISC", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 357)]
    [XmlElement("S_ISC")]
    public Decimal S_Isc
    { 
       get
       {
          return _S_Isc;
       }
       set
       {
          _S_Isc = value;
       }
    }
    private Decimal _S_Isc;

    [RfcField(AbapName = "S_OTROST", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 365)]
    [XmlElement("S_OTROST")]
    public Decimal S_Otrost
    { 
       get
       {
          return _S_Otrost;
       }
       set
       {
          _S_Otrost = value;
       }
    }
    private Decimal _S_Otrost;

    [RfcField(AbapName = "S_OTROSC", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 373)]
    [XmlElement("S_OTROSC")]
    public Decimal S_Otrosc
    { 
       get
       {
          return _S_Otrosc;
       }
       set
       {
          _S_Otrosc = value;
       }
    }
    private Decimal _S_Otrosc;

    [RfcField(AbapName = "T_DESCUENTOS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 381)]
    [XmlElement("T_DESCUENTOS")]
    public Decimal T_Descuentos
    { 
       get
       {
          return _T_Descuentos;
       }
       set
       {
          _T_Descuentos = value;
       }
    }
    private Decimal _T_Descuentos;

    [RfcField(AbapName = "IT_VT_CESESION", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 389)]
    [XmlElement("IT_VT_CESESION")]
    public Decimal It_Vt_Cesesion
    { 
       get
       {
          return _It_Vt_Cesesion;
       }
       set
       {
          _It_Vt_Cesesion = value;
       }
    }
    private Decimal _It_Vt_Cesesion;

    [RfcField(AbapName = "LEYENDA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 100, Offset = 397)]
    [XmlElement("LEYENDA")]
    public string Leyenda
    { 
       get
       {
          return _Leyenda;
       }
       set
       {
          _Leyenda = value;
       }
    }
    private string _Leyenda;

    [RfcField(AbapName = "GUIAREMISION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 35, Offset = 497)]
    [XmlElement("GUIAREMISION")]
    public string Guiaremision
    { 
       get
       {
          return _Guiaremision;
       }
       set
       {
          _Guiaremision = value;
       }
    }
    private string _Guiaremision;

    [RfcField(AbapName = "MONEDA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Offset = 532)]
    [XmlElement("MONEDA")]
    public string Moneda
    { 
       get
       {
          return _Moneda;
       }
       set
       {
          _Moneda = value;
       }
    }
    private string _Moneda;

    [RfcField(AbapName = "TASAIGV", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Decimals = 2, Offset = 537)]
    [XmlElement("TASAIGV")]
    public Decimal Tasaigv
    { 
       get
       {
          return _Tasaigv;
       }
       set
       {
          _Tasaigv = value;
       }
    }
    private Decimal _Tasaigv;

    [RfcField(AbapName = "AJUSTE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Decimals = 2, Offset = 543)]
    [XmlElement("AJUSTE")]
    public Decimal Ajuste
    { 
       get
       {
          return _Ajuste;
       }
       set
       {
          _Ajuste = value;
       }
    }
    private Decimal _Ajuste;

    [RfcField(AbapName = "TIPONCND", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 549)]
    [XmlElement("TIPONCND")]
    public string Tiponcnd
    { 
       get
       {
          return _Tiponcnd;
       }
       set
       {
          _Tiponcnd = value;
       }
    }
    private string _Tiponcnd;

    [RfcField(AbapName = "MOTIVONCND", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 250, Offset = 551)]
    [XmlElement("MOTIVONCND")]
    public string Motivoncnd
    { 
       get
       {
          return _Motivoncnd;
       }
       set
       {
          _Motivoncnd = value;
       }
    }
    private string _Motivoncnd;

    [RfcField(AbapName = "DOCREFERENCIA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Offset = 801)]
    [XmlElement("DOCREFERENCIA")]
    public string Docreferencia
    { 
       get
       {
          return _Docreferencia;
       }
       set
       {
          _Docreferencia = value;
       }
    }
    private string _Docreferencia;

    [RfcField(AbapName = "TIPODOCREFERENCIA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 814)]
    [XmlElement("TIPODOCREFERENCIA")]
    public string Tipodocreferencia
    { 
       get
       {
          return _Tipodocreferencia;
       }
       set
       {
          _Tipodocreferencia = value;
       }
    }
    private string _Tipodocreferencia;

    [RfcField(AbapName = "ORDENCOMPRA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 816)]
    [XmlElement("ORDENCOMPRA")]
    public string Ordencompra
    { 
       get
       {
          return _Ordencompra;
       }
       set
       {
          _Ordencompra = value;
       }
    }
    private string _Ordencompra;

    [RfcField(AbapName = "DIRECCLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 100, Offset = 826)]
    [XmlElement("DIRECCLIENTE")]
    public string Direccliente
    { 
       get
       {
          return _Direccliente;
       }
       set
       {
          _Direccliente = value;
       }
    }
    private string _Direccliente;

    [RfcField(AbapName = "OTROSCONTRIB", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 926)]
    [XmlElement("OTROSCONTRIB")]
    public string Otroscontrib
    { 
       get
       {
          return _Otroscontrib;
       }
       set
       {
          _Otroscontrib = value;
       }
    }
    private string _Otroscontrib;

    [RfcField(AbapName = "HASHCODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 930)]
    [XmlElement("HASHCODE")]
    public string Hashcode
    { 
       get
       {
          return _Hashcode;
       }
       set
       {
          _Hashcode = value;
       }
    }
    private string _Hashcode;

    [RfcField(AbapName = "E_MAIL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 100, Offset = 970)]
    [XmlElement("E_MAIL")]
    public string E_Mail
    { 
       get
       {
          return _E_Mail;
       }
       set
       {
          _E_Mail = value;
       }
    }
    private string _E_Mail;

    [RfcField(AbapName = "CODLEYENDA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 1070)]
    [XmlElement("CODLEYENDA")]
    public string Codleyenda
    { 
       get
       {
          return _Codleyenda;
       }
       set
       {
          _Codleyenda = value;
       }
    }
    private string _Codleyenda;

    [RfcField(AbapName = "FLAGDETRACCION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 1074)]
    [XmlElement("FLAGDETRACCION")]
    public string Flagdetraccion
    { 
       get
       {
          return _Flagdetraccion;
       }
       set
       {
          _Flagdetraccion = value;
       }
    }
    private string _Flagdetraccion;

    [RfcField(AbapName = "UBIGEO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Offset = 1075)]
    [XmlElement("UBIGEO")]
    public string Ubigeo
    { 
       get
       {
          return _Ubigeo;
       }
       set
       {
          _Ubigeo = value;
       }
    }
    private string _Ubigeo;

  }

}
