
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 20/07/2015
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  [RfcStructure(AbapName ="ZFE_DETALLE" , Length = 185)]
  public class ZFE_DETALLE : SAPStructure
  {
    
    [RfcField(AbapName = "NROORDEN", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Offset = 0)]
    [XmlElement("NROORDEN")]
    public string Nroorden
    { 
       get
       {
          return _Nroorden;
       }
       set
       {
          _Nroorden = value;
       }
    }
    private string _Nroorden;

    [RfcField(AbapName = "UNIDADMEDIDA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 6)]
    [XmlElement("UNIDADMEDIDA")]
    public string Unidadmedida
    { 
       get
       {
          return _Unidadmedida;
       }
       set
       {
          _Unidadmedida = value;
       }
    }
    private string _Unidadmedida;

    [RfcField(AbapName = "UNIXITEM", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 3, Offset = 9)]
    [XmlElement("UNIXITEM")]
    public Decimal Unixitem
    { 
       get
       {
          return _Unixitem;
       }
       set
       {
          _Unixitem = value;
       }
    }
    private Decimal _Unixitem;

    [RfcField(AbapName = "CODPROD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Offset = 17)]
    [XmlElement("CODPROD")]
    public string Codprod
    { 
       get
       {
          return _Codprod;
       }
       set
       {
          _Codprod = value;
       }
    }
    private string _Codprod;

    [RfcField(AbapName = "DESCRIPCION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 50, Offset = 35)]
    [XmlElement("DESCRIPCION")]
    public string Descripcion
    { 
       get
       {
          return _Descripcion;
       }
       set
       {
          _Descripcion = value;
       }
    }
    private string _Descripcion;

    [RfcField(AbapName = "PV_UNI_I_CONIGV", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 85)]
    [XmlElement("PV_UNI_I_CONIGV")]
    public Decimal Pv_Uni_I_Conigv
    { 
       get
       {
          return _Pv_Uni_I_Conigv;
       }
       set
       {
          _Pv_Uni_I_Conigv = value;
       }
    }
    private Decimal _Pv_Uni_I_Conigv;

    [RfcField(AbapName = "VR_I_NO_ONE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 92)]
    [XmlElement("VR_I_NO_ONE")]
    public Decimal Vr_I_No_One
    { 
       get
       {
          return _Vr_I_No_One;
       }
       set
       {
          _Vr_I_No_One = value;
       }
    }
    private Decimal _Vr_I_No_One;

    [RfcField(AbapName = "AFEC_IGV_I", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 99)]
    [XmlElement("AFEC_IGV_I")]
    public string Afec_Igv_I
    { 
       get
       {
          return _Afec_Igv_I;
       }
       set
       {
          _Afec_Igv_I = value;
       }
    }
    private string _Afec_Igv_I;

    [RfcField(AbapName = "IGV_ITEM", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 101)]
    [XmlElement("IGV_ITEM")]
    public Decimal Igv_Item
    { 
       get
       {
          return _Igv_Item;
       }
       set
       {
          _Igv_Item = value;
       }
    }
    private Decimal _Igv_Item;

    [RfcField(AbapName = "S_IGV_ITEM", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 108)]
    [XmlElement("S_IGV_ITEM")]
    public Decimal S_Igv_Item
    { 
       get
       {
          return _S_Igv_Item;
       }
       set
       {
          _S_Igv_Item = value;
       }
    }
    private Decimal _S_Igv_Item;

    [RfcField(AbapName = "S_ISC_ITEM", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 115)]
    [XmlElement("S_ISC_ITEM")]
    public Decimal S_Isc_Item
    { 
       get
       {
          return _S_Isc_Item;
       }
       set
       {
          _S_Isc_Item = value;
       }
    }
    private Decimal _S_Isc_Item;

    [RfcField(AbapName = "V_VT_U_ITEM", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 122)]
    [XmlElement("V_VT_U_ITEM")]
    public Decimal V_Vt_U_Item
    { 
       get
       {
          return _V_Vt_U_Item;
       }
       set
       {
          _V_Vt_U_Item = value;
       }
    }
    private Decimal _V_Vt_U_Item;

    [RfcField(AbapName = "V_VT_ITEM", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 129)]
    [XmlElement("V_VT_ITEM")]
    public Decimal V_Vt_Item
    { 
       get
       {
          return _V_Vt_Item;
       }
       set
       {
          _V_Vt_Item = value;
       }
    }
    private Decimal _V_Vt_Item;

    [RfcField(AbapName = "T_VN_AFECTAS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 136)]
    [XmlElement("T_VN_AFECTAS")]
    public Decimal T_Vn_Afectas
    { 
       get
       {
          return _T_Vn_Afectas;
       }
       set
       {
          _T_Vn_Afectas = value;
       }
    }
    private Decimal _T_Vn_Afectas;

    [RfcField(AbapName = "T_VN_INAFECT", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 143)]
    [XmlElement("T_VN_INAFECT")]
    public Decimal T_Vn_Inafect
    { 
       get
       {
          return _T_Vn_Inafect;
       }
       set
       {
          _T_Vn_Inafect = value;
       }
    }
    private Decimal _T_Vn_Inafect;

    [RfcField(AbapName = "T_VN_EXONERA", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 150)]
    [XmlElement("T_VN_EXONERA")]
    public Decimal T_Vn_Exonera
    { 
       get
       {
          return _T_Vn_Exonera;
       }
       set
       {
          _T_Vn_Exonera = value;
       }
    }
    private Decimal _T_Vn_Exonera;

    [RfcField(AbapName = "T_DESCUENTOS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 157)]
    [XmlElement("T_DESCUENTOS")]
    public Decimal T_Descuentos
    { 
       get
       {
          return _T_Descuentos;
       }
       set
       {
          _T_Descuentos = value;
       }
    }
    private Decimal _T_Descuentos;

    [RfcField(AbapName = "IT_VT_CESESION", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 164)]
    [XmlElement("IT_VT_CESESION")]
    public Decimal It_Vt_Cesesion
    { 
       get
       {
          return _It_Vt_Cesesion;
       }
       set
       {
          _It_Vt_Cesesion = value;
       }
    }
    private Decimal _It_Vt_Cesesion;

    [RfcField(AbapName = "V_REF_U_NONE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 171)]
    [XmlElement("V_REF_U_NONE")]
    public Decimal V_Ref_U_None
    { 
       get
       {
          return _V_Ref_U_None;
       }
       set
       {
          _V_Ref_U_None = value;
       }
    }
    private Decimal _V_Ref_U_None;

    [RfcField(AbapName = "AJUSTE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 178)]
    [XmlElement("AJUSTE")]
    public Decimal Ajuste
    { 
       get
       {
          return _Ajuste;
       }
       set
       {
          _Ajuste = value;
       }
    }
    private Decimal _Ajuste;

  }

}
