
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 22/10/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  public class ZPV_ST_LISTA_IMPRESORASTable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZPV_ST_LISTA_IMPRESORAS));
    }
 
    public override object CreateNewRow()
    { 
        return new ZPV_ST_LISTA_IMPRESORAS();
    }
     
    public ZPV_ST_LISTA_IMPRESORAS this[int index] 
    {
        get 
        {
            return ((ZPV_ST_LISTA_IMPRESORAS)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZPV_ST_LISTA_IMPRESORAS value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZPV_ST_LISTA_IMPRESORAS value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZPV_ST_LISTA_IMPRESORAS value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZPV_ST_LISTA_IMPRESORAS value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZPV_ST_LISTA_IMPRESORAS value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZPV_ST_LISTA_IMPRESORAS[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
