
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 22/10/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  public class ZST_USUARIOTable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZST_USUARIO));
    }
 
    public override object CreateNewRow()
    { 
        return new ZST_USUARIO();
    }
     
    public ZST_USUARIO this[int index] 
    {
        get 
        {
            return ((ZST_USUARIO)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZST_USUARIO value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZST_USUARIO value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZST_USUARIO value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZST_USUARIO value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZST_USUARIO value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZST_USUARIO[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
