
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 22/10/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  [RfcStructure(AbapName ="ZST_PV_DATOS_VENDEDOR" , Length = 99)]
  public class ZST_PV_DATOS_VENDEDOR : SAPStructure
  {
    
    [RfcField(AbapName = "USUARIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 0)]
    [XmlElement("USUARIO")]
    public string Usuario
    { 
       get
       {
          return _Usuario;
       }
       set
       {
          _Usuario = value;
       }
    }
    private string _Usuario;

    [RfcField(AbapName = "NOMBRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 10)]
    [XmlElement("NOMBRE")]
    public string Nombre
    { 
       get
       {
          return _Nombre;
       }
       set
       {
          _Nombre = value;
       }
    }
    private string _Nombre;

    [RfcField(AbapName = "OFICINA_VENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 50)]
    [XmlElement("OFICINA_VENTA")]
    public string Oficina_Venta
    { 
       get
       {
          return _Oficina_Venta;
       }
       set
       {
          _Oficina_Venta = value;
       }
    }
    private string _Oficina_Venta;

    [RfcField(AbapName = "DENOM_OFICINA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 54)]
    [XmlElement("DENOM_OFICINA")]
    public string Denom_Oficina
    { 
       get
       {
          return _Denom_Oficina;
       }
       set
       {
          _Denom_Oficina = value;
       }
    }
    private string _Denom_Oficina;

    [RfcField(AbapName = "OFICINA_ALTER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 74)]
    [XmlElement("OFICINA_ALTER")]
    public string Oficina_Alter
    { 
       get
       {
          return _Oficina_Alter;
       }
       set
       {
          _Oficina_Alter = value;
       }
    }
    private string _Oficina_Alter;

    [RfcField(AbapName = "DEN_OFIC_ALT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 78)]
    [XmlElement("DEN_OFIC_ALT")]
    public string Den_Ofic_Alt
    { 
       get
       {
          return _Den_Ofic_Alt;
       }
       set
       {
          _Den_Ofic_Alt = value;
       }
    }
    private string _Den_Ofic_Alt;

    [RfcField(AbapName = "T_USER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 98)]
    [XmlElement("T_USER")]
    public string T_User
    { 
       get
       {
          return _T_User;
       }
       set
       {
          _T_User = value;
       }
    }
    private string _T_User;

  }

}
