
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 22/10/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  [RfcStructure(AbapName ="ZST_PV_COMPRO_CABECERA" , Length = 628)]
  public class ZST_PV_COMPRO_CABECERA : SAPStructure
  {
    
    [RfcField(AbapName = "NOM_CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 0)]
    [XmlElement("NOM_CLIENTE")]
    public string Nom_Cliente
    { 
       get
       {
          return _Nom_Cliente;
       }
       set
       {
          _Nom_Cliente = value;
       }
    }
    private string _Nom_Cliente;

    [RfcField(AbapName = "DIR_CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 100, Offset = 40)]
    [XmlElement("DIR_CLIENTE")]
    public string Dir_Cliente
    { 
       get
       {
          return _Dir_Cliente;
       }
       set
       {
          _Dir_Cliente = value;
       }
    }
    private string _Dir_Cliente;

    [RfcField(AbapName = "DOC_CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 140)]
    [XmlElement("DOC_CLIENTE")]
    public string Doc_Cliente
    { 
       get
       {
          return _Doc_Cliente;
       }
       set
       {
          _Doc_Cliente = value;
       }
    }
    private string _Doc_Cliente;

    [RfcField(AbapName = "FEC_DOCUMENTO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 156)]
    [XmlElement("FEC_DOCUMENTO")]
    public string Fec_Documento
    { 
       get
       {
          return _Fec_Documento;
       }
       set
       {
          _Fec_Documento = value;
       }
    }
    private string _Fec_Documento;

    [RfcField(AbapName = "NRO_SAP_PVU", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 164)]
    [XmlElement("NRO_SAP_PVU")]
    public string Nro_Sap_Pvu
    { 
       get
       {
          return _Nro_Sap_Pvu;
       }
       set
       {
          _Nro_Sap_Pvu = value;
       }
    }
    private string _Nro_Sap_Pvu;

    [RfcField(AbapName = "NRO_REFERENCIA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Offset = 174)]
    [XmlElement("NRO_REFERENCIA")]
    public string Nro_Referencia
    { 
       get
       {
          return _Nro_Referencia;
       }
       set
       {
          _Nro_Referencia = value;
       }
    }
    private string _Nro_Referencia;

    [RfcField(AbapName = "COD_VENDEDOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 192)]
    [XmlElement("COD_VENDEDOR")]
    public string Cod_Vendedor
    { 
       get
       {
          return _Cod_Vendedor;
       }
       set
       {
          _Cod_Vendedor = value;
       }
    }
    private string _Cod_Vendedor;

    [RfcField(AbapName = "NOM_VENDEDOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 202)]
    [XmlElement("NOM_VENDEDOR")]
    public string Nom_Vendedor
    { 
       get
       {
          return _Nom_Vendedor;
       }
       set
       {
          _Nom_Vendedor = value;
       }
    }
    private string _Nom_Vendedor;

    [RfcField(AbapName = "CLA_MENSAJE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 242)]
    [XmlElement("CLA_MENSAJE")]
    public string Cla_Mensaje
    { 
       get
       {
          return _Cla_Mensaje;
       }
       set
       {
          _Cla_Mensaje = value;
       }
    }
    private string _Cla_Mensaje;

    [RfcField(AbapName = "REC_EFECTIVA", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 246)]
    [XmlElement("REC_EFECTIVA")]
    public Decimal Rec_Efectiva
    { 
       get
       {
          return _Rec_Efectiva;
       }
       set
       {
          _Rec_Efectiva = value;
       }
    }
    private Decimal _Rec_Efectiva;

    [RfcField(AbapName = "NOMBRES", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 253)]
    [XmlElement("NOMBRES")]
    public string Nombres
    { 
       get
       {
          return _Nombres;
       }
       set
       {
          _Nombres = value;
       }
    }
    private string _Nombres;

    [RfcField(AbapName = "APELLIDOS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 293)]
    [XmlElement("APELLIDOS")]
    public string Apellidos
    { 
       get
       {
          return _Apellidos;
       }
       set
       {
          _Apellidos = value;
       }
    }
    private string _Apellidos;

    [RfcField(AbapName = "F_NACIMIENTO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 333)]
    [XmlElement("F_NACIMIENTO")]
    public string F_Nacimiento
    { 
       get
       {
          return _F_Nacimiento;
       }
       set
       {
          _F_Nacimiento = value;
       }
    }
    private string _F_Nacimiento;

    [RfcField(AbapName = "TELEFONO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 341)]
    [XmlElement("TELEFONO")]
    public string Telefono
    { 
       get
       {
          return _Telefono;
       }
       set
       {
          _Telefono = value;
       }
    }
    private string _Telefono;

    [RfcField(AbapName = "TIPO_DOCUMENTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 357)]
    [XmlElement("TIPO_DOCUMENTO")]
    public string Tipo_Documento
    { 
       get
       {
          return _Tipo_Documento;
       }
       set
       {
          _Tipo_Documento = value;
       }
    }
    private string _Tipo_Documento;

    [RfcField(AbapName = "UBIGEO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 9, Offset = 359)]
    [XmlElement("UBIGEO")]
    public string Ubigeo
    { 
       get
       {
          return _Ubigeo;
       }
       set
       {
          _Ubigeo = value;
       }
    }
    private string _Ubigeo;

    [RfcField(AbapName = "IP_PRINTER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 32, Offset = 368)]
    [XmlElement("IP_PRINTER")]
    public string Ip_Printer
    { 
       get
       {
          return _Ip_Printer;
       }
       set
       {
          _Ip_Printer = value;
       }
    }
    private string _Ip_Printer;

    [RfcField(AbapName = "NAME_PRINTER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 50, Offset = 400)]
    [XmlElement("NAME_PRINTER")]
    public string Name_Printer
    { 
       get
       {
          return _Name_Printer;
       }
       set
       {
          _Name_Printer = value;
       }
    }
    private string _Name_Printer;

    [RfcField(AbapName = "NREFORIG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 450)]
    [XmlElement("NREFORIG")]
    public string Nreforig
    { 
       get
       {
          return _Nreforig;
       }
       set
       {
          _Nreforig = value;
       }
    }
    private string _Nreforig;

    [RfcField(AbapName = "DIRECCION_PDV", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 100, Offset = 466)]
    [XmlElement("DIRECCION_PDV")]
    public string Direccion_Pdv
    { 
       get
       {
          return _Direccion_Pdv;
       }
       set
       {
          _Direccion_Pdv = value;
       }
    }
    private string _Direccion_Pdv;

    [RfcField(AbapName = "NRO_REF_CORNER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 566)]
    [XmlElement("NRO_REF_CORNER")]
    public string Nro_Ref_Corner
    { 
       get
       {
          return _Nro_Ref_Corner;
       }
       set
       {
          _Nro_Ref_Corner = value;
       }
    }
    private string _Nro_Ref_Corner;

    [RfcField(AbapName = "TIPO_DOC_CORNER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 606)]
    [XmlElement("TIPO_DOC_CORNER")]
    public string Tipo_Doc_Corner
    { 
       get
       {
          return _Tipo_Doc_Corner;
       }
       set
       {
          _Tipo_Doc_Corner = value;
       }
    }
    private string _Tipo_Doc_Corner;

    [RfcField(AbapName = "ENTREGA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 610)]
    [XmlElement("ENTREGA")]
    public string Entrega
    { 
       get
       {
          return _Entrega;
       }
       set
       {
          _Entrega = value;
       }
    }
    private string _Entrega;

    [RfcField(AbapName = "FECHA_MOV_REAL", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 620)]
    [XmlElement("FECHA_MOV_REAL")]
    public string Fecha_Mov_Real
    { 
       get
       {
          return _Fecha_Mov_Real;
       }
       set
       {
          _Fecha_Mov_Real = value;
       }
    }
    private string _Fecha_Mov_Real;

  }

}
