
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 22/10/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Pagos
{

  [RfcStructure(AbapName ="ZST_PRV_DETALLE2" , Length = 194)]
  public class ZST_PRV_DETALLE2 : SAPStructure
  {
    
    [RfcField(AbapName = "MANDT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 0)]
    [XmlElement("MANDT")]
    public string Mandt
    { 
       get
       {
          return _Mandt;
       }
       set
       {
          _Mandt = value;
       }
    }
    private string _Mandt;

    [RfcField(AbapName = "NUMBR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 3)]
    [XmlElement("NUMBR")]
    public string Numbr
    { 
       get
       {
          return _Numbr;
       }
       set
       {
          _Numbr = value;
       }
    }
    private string _Numbr;

    [RfcField(AbapName = "POSNR", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Offset = 13)]
    [XmlElement("POSNR")]
    public string Posnr
    { 
       get
       {
          return _Posnr;
       }
       set
       {
          _Posnr = value;
       }
    }
    private string _Posnr;

    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Offset = 19)]
    [XmlElement("MATNR")]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;

    [RfcField(AbapName = "MAKTX", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 37)]
    [XmlElement("MAKTX")]
    public string Maktx
    { 
       get
       {
          return _Maktx;
       }
       set
       {
          _Maktx = value;
       }
    }
    private string _Maktx;

    [RfcField(AbapName = "MENGE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 3, Offset = 77)]
    [XmlElement("MENGE")]
    public Decimal Menge
    { 
       get
       {
          return _Menge;
       }
       set
       {
          _Menge = value;
       }
    }
    private Decimal _Menge;

    [RfcField(AbapName = "VKAUS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 84)]
    [XmlElement("VKAUS")]
    public string Vkaus
    { 
       get
       {
          return _Vkaus;
       }
       set
       {
          _Vkaus = value;
       }
    }
    private string _Vkaus;

    [RfcField(AbapName = "DESC_UTIL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 87)]
    [XmlElement("DESC_UTIL")]
    public string Desc_Util
    { 
       get
       {
          return _Desc_Util;
       }
       set
       {
          _Desc_Util = value;
       }
    }
    private string _Desc_Util;

    [RfcField(AbapName = "CAMPANA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 107)]
    [XmlElement("CAMPANA")]
    public string Campana
    { 
       get
       {
          return _Campana;
       }
       set
       {
          _Campana = value;
       }
    }
    private string _Campana;

    [RfcField(AbapName = "DESC_CAMP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 111)]
    [XmlElement("DESC_CAMP")]
    public string Desc_Camp
    { 
       get
       {
          return _Desc_Camp;
       }
       set
       {
          _Desc_Camp = value;
       }
    }
    private string _Desc_Camp;

    [RfcField(AbapName = "PLAN_TARIFARIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 151)]
    [XmlElement("PLAN_TARIFARIO")]
    public string Plan_Tarifario
    { 
       get
       {
          return _Plan_Tarifario;
       }
       set
       {
          _Plan_Tarifario = value;
       }
    }
    private string _Plan_Tarifario;

    [RfcField(AbapName = "DESC_PLTR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 154)]
    [XmlElement("DESC_PLTR")]
    public string Desc_Pltr
    { 
       get
       {
          return _Desc_Pltr;
       }
       set
       {
          _Desc_Pltr = value;
       }
    }
    private string _Desc_Pltr;

  }

}
