'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace WSSimCards
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SimcardsPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ws/sap/simcards"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(itDataType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(itReturnType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(itNumTelefType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(gtOutTabType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(esResumenType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(etDetalleType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(itWorkType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(itNroTelType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(nroSimcardsDataType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(itMatSerType())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(itTelSerType()))>  _
    Public Class ebsSimcards
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://172.19.74.68:8909/SimcardsWS/ebsSimcards"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/consultarTelefonoDisp", RequestElementName:="consultarTelefonoDispRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultarTelefonoDisp(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> ByVal cantidadTelef As String, ByVal clasifRed As String, ByVal tipoCliente As String, ByVal codigoNacional As String, ByVal tipoNroTelef As String, ByVal codigoHlr As String, ByVal nroTelef As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itDataRow", IsNullable:=false)> ByRef itData() As itDataType, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("consultarTelefonoDisp", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, cantidadTelef, clasifRed, tipoCliente, codigoNacional, tipoNroTelef, codigoHlr, nroTelef})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itData = CType(results(3),itDataType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarTelefonoDisp(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal cantidadTelef As String, ByVal clasifRed As String, ByVal tipoCliente As String, ByVal codigoNacional As String, ByVal tipoNroTelef As String, ByVal codigoHlr As String, ByVal nroTelef As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarTelefonoDisp", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, cantidadTelef, clasifRed, tipoCliente, codigoNacional, tipoNroTelef, codigoHlr, nroTelef}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarTelefonoDisp(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itData() As itDataType, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itData = CType(results(3),itDataType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/consultarTelefonoTodos", RequestElementName:="consultarTelefonoTodosRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultarTelefonoTodos(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itNumTelefRow", IsNullable:=false)> ByRef itNumTelef() As itNumTelefType, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("consultarTelefonoTodos", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itNumTelef = CType(results(3),itNumTelefType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarTelefonoTodos(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarTelefonoTodos", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarTelefonoTodos(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itNumTelef() As itNumTelefType, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itNumTelef = CType(results(3),itNumTelefType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/consultarStatusTelefono", RequestElementName:="consultarStatusTelefonoRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultarStatusTelefono(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal nroSerie As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("gtOutTabRow", IsNullable:=false)> ByRef gtOutTab() As gtOutTabType, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("consultarStatusTelefono", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, nroSerie})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            gtOutTab = CType(results(3),gtOutTabType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarStatusTelefono(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal nroSerie As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarStatusTelefono", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, nroSerie}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarStatusTelefono(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef gtOutTab() As gtOutTabType, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            gtOutTab = CType(results(3),gtOutTabType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/cambiarStatusTelefono", RequestElementName:="cambiarStatusTelefonoRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cambiarStatusTelefono( _
                    ByRef idTransaccion As String,  _
                    ByVal ipAplicacion As String,  _
                    ByVal nombreAplicacion As String,  _
                    ByVal usuarioAplicacion As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> ByVal cantNro As String,  _
                    ByVal [region] As String,  _
                    ByVal clasifRed As String,  _
                    ByVal codigoHlr As String,  _
                    ByVal tipoCliente As String,  _
                    ByVal statusInicial As String,  _
                    ByVal statusFinal As String,  _
                    ByVal usuario As String,  _
                    ByRef mensajeResultado As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> ByRef subRc As String,  _
                    <System.Xml.Serialization.XmlArrayItemAttribute("esResumenRow", IsNullable:=false)> ByRef esResumen() As esResumenType,  _
                    <System.Xml.Serialization.XmlArrayItemAttribute("etDetalleRow", IsNullable:=false)> ByRef etDetalle() As etDetalleType,  _
                    <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("cambiarStatusTelefono", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, cantNro, [region], clasifRed, codigoHlr, tipoCliente, statusInicial, statusFinal, usuario})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            subRc = CType(results(3),String)
            esResumen = CType(results(4),esResumenType())
            etDetalle = CType(results(5),etDetalleType())
            itReturn = CType(results(6),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegincambiarStatusTelefono(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal cantNro As String, ByVal [region] As String, ByVal clasifRed As String, ByVal codigoHlr As String, ByVal tipoCliente As String, ByVal statusInicial As String, ByVal statusFinal As String, ByVal usuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("cambiarStatusTelefono", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, cantNro, [region], clasifRed, codigoHlr, tipoCliente, statusInicial, statusFinal, usuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcambiarStatusTelefono(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef subRc As String, ByRef esResumen() As esResumenType, ByRef etDetalle() As etDetalleType, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            subRc = CType(results(3),String)
            esResumen = CType(results(4),esResumenType())
            etDetalle = CType(results(5),etDetalleType())
            itReturn = CType(results(6),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/cambiarStatus", RequestElementName:="cambiarStatusRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cambiarStatus(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal status As String, ByVal usuario As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("cambiarStatus", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, status, usuario})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegincambiarStatus(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal status As String, ByVal usuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("cambiarStatus", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, status, usuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcambiarStatus(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/reversionCambioNumero", RequestElementName:="reversionCambioNumeroRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function reversionCambioNumero(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal telefAn As String, ByVal telefNv As String, ByVal usuario As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("reversionCambioNumero", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, telefAn, telefNv, usuario})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginreversionCambioNumero(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal telefAn As String, ByVal telefNv As String, ByVal usuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("reversionCambioNumero", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, telefAn, telefNv, usuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndreversionCambioNumero(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/registroIMSIPortabilidad", RequestElementName:="registroIMSIPortabilidadRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function registroIMSIPortabilidad(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal clasifRed As String, ByVal tipoNroTelef As String, ByVal nroSerie As String, ByVal tipoCliente As String, ByVal [region] As String, ByVal material As String, ByVal usuario As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("registroIMSIPortabilidad", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, clasifRed, tipoNroTelef, nroSerie, tipoCliente, [region], material, usuario})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginregistroIMSIPortabilidad(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal clasifRed As String, ByVal tipoNroTelef As String, ByVal nroSerie As String, ByVal tipoCliente As String, ByVal [region] As String, ByVal material As String, ByVal usuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("registroIMSIPortabilidad", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, clasifRed, tipoNroTelef, nroSerie, tipoCliente, [region], material, usuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndregistroIMSIPortabilidad(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/actualizarNroTelef", RequestElementName:="actualizarNroTelefRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function actualizarNroTelef(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal telefAn As String, ByVal telefNv As String, ByVal usuario As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("actualizarNroTelef", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, telefAn, telefNv, usuario})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginactualizarNroTelef(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal telefAn As String, ByVal telefNv As String, ByVal usuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("actualizarNroTelef", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, telefAn, telefNv, usuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndactualizarNroTelef(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/eliminarNroTelef", RequestElementName:="eliminarNroTelefRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function eliminarNroTelef(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal usuario As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("eliminarNroTelef", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, usuario})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegineliminarNroTelef(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal usuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("eliminarNroTelef", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, usuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndeliminarNroTelef(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/listarMSISDNreserva", RequestElementName:="listarMSISDNreservaRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listarMSISDNreserva( _
                    ByRef idTransaccion As String,  _
                    ByVal ipAplicacion As String,  _
                    ByVal nombreAplicacion As String,  _
                    ByVal usuarioAplicacion As String,  _
                    ByVal [region] As String,  _
                    ByVal clasifRed As String,  _
                    ByVal codigoHlr As String,  _
                    ByVal tipoNroTelef As String,  _
                    ByVal tipoCliente As String,  _
                    ByVal clasifDesti As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> ByVal cantidadBuscar As String,  _
                    ByVal status As String,  _
                    ByRef mensajeResultado As String,  _
                    <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType,  _
                    <System.Xml.Serialization.XmlArrayItemAttribute("itWorkRow", IsNullable:=false)> ByRef itWork() As itWorkType,  _
                    <System.Xml.Serialization.XmlArrayItemAttribute("itNroTelRow", IsNullable:=false)> ByRef itNroTel() As itNroTelType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("listarMSISDNreserva", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, [region], clasifRed, codigoHlr, tipoNroTelef, tipoCliente, clasifDesti, cantidadBuscar, status})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            itWork = CType(results(4),itWorkType())
            itNroTel = CType(results(5),itNroTelType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginlistarMSISDNreserva(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal [region] As String, ByVal clasifRed As String, ByVal codigoHlr As String, ByVal tipoNroTelef As String, ByVal tipoCliente As String, ByVal clasifDesti As String, ByVal cantidadBuscar As String, ByVal status As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("listarMSISDNreserva", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, [region], clasifRed, codigoHlr, tipoNroTelef, tipoCliente, clasifDesti, cantidadBuscar, status}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlistarMSISDNreserva(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itReturn() As itReturnType, ByRef itWork() As itWorkType, ByRef itNroTel() As itNroTelType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itReturn = CType(results(3),itReturnType())
            itWork = CType(results(4),itWorkType())
            itNroTel = CType(results(5),itNroTelType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/rollbackPelVendido", RequestElementName:="rollbackPelVendidoRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function rollbackPelVendido(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroSerie As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> ByRef subRc As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("rollbackPelVendido", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroSerie})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            subRc = CType(results(3),String)
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginrollbackPelVendido(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroSerie As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("rollbackPelVendido", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroSerie}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndrollbackPelVendido(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef subRc As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            subRc = CType(results(3),String)
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/cambiarStatusVendido", RequestElementName:="cambiarStatusVendidoRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cambiarStatusVendido(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal usuario As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> ByRef subRc As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("cambiarStatusVendido", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, usuario})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            subRc = CType(results(3),String)
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegincambiarStatusVendido(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal usuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("cambiarStatusVendido", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, usuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcambiarStatusVendido(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef subRc As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            subRc = CType(results(3),String)
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/obtenerDatosNroTelef", RequestElementName:="obtenerDatosNroTelefRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtenerDatosNroTelef(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal material As String, ByVal nroSerie As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("nroSimcardsDataRow", IsNullable:=false)> ByRef nroSimcardsData() As nroSimcardsDataType, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("obtenerDatosNroTelef", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, material, nroSerie})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            nroSimcardsData = CType(results(3),nroSimcardsDataType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginobtenerDatosNroTelef(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal material As String, ByVal nroSerie As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtenerDatosNroTelef", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, material, nroSerie}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtenerDatosNroTelef(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef nroSimcardsData() As nroSimcardsDataType, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            nroSimcardsData = CType(results(3),nroSimcardsDataType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/obtenerNroTelefSerie", RequestElementName:="obtenerNroTelefSerieRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtenerNroTelefSerie(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByRef nroTelef As String, ByRef nroSerie As String, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("obtenerNroTelefSerie", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, nroSerie})
            idTransaccion = CType(results(1),String)
            nroTelef = CType(results(2),String)
            nroSerie = CType(results(3),String)
            mensajeResultado = CType(results(4),String)
            itReturn = CType(results(5),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginobtenerNroTelefSerie(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal nroSerie As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtenerNroTelefSerie", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef, nroSerie}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtenerNroTelefSerie(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef nroTelef As String, ByRef nroSerie As String, ByRef mensajeResultado As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            nroTelef = CType(results(2),String)
            nroSerie = CType(results(3),String)
            mensajeResultado = CType(results(4),String)
            itReturn = CType(results(5),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/obtenerNroTelef", RequestElementName:="obtenerNroTelefRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtenerNroTelef(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, <System.Xml.Serialization.XmlArrayItemAttribute("itInputRow", IsNullable:=false)> ByVal itInput() As itMatSerType, ByRef mensajeResultado As String, <System.Xml.Serialization.XmlArrayItemAttribute("itOutputRow", IsNullable:=false)> ByRef itOutput() As itTelSerType, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("obtenerNroTelef", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, itInput})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itOutput = CType(results(3),itTelSerType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginobtenerNroTelef(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal itInput() As itMatSerType, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtenerNroTelef", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, itInput}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtenerNroTelef(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef itOutput() As itTelSerType, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            itOutput = CType(results(3),itTelSerType())
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/sap/simcards/obtenerNroTelef", RequestElementName:="obtenerHLRRequest", RequestNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", ResponseNamespace:="http://claro.com.pe/eai/ws/sap/simcards/types", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function obtenerHLR(ByRef idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByRef mensajeResultado As String, ByRef codigoHlr As String, <System.Xml.Serialization.XmlArrayItemAttribute("itReturnRow", IsNullable:=false)> ByRef itReturn() As itReturnType) As <System.Xml.Serialization.XmlElementAttribute("codigoResultado")> String
            Dim results() As Object = Me.Invoke("obtenerHLR", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef})
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            codigoHlr = CType(results(3),String)
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginobtenerHLR(ByVal idTransaccion As String, ByVal ipAplicacion As String, ByVal nombreAplicacion As String, ByVal usuarioAplicacion As String, ByVal nroTelef As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("obtenerHLR", New Object() {idTransaccion, ipAplicacion, nombreAplicacion, usuarioAplicacion, nroTelef}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndobtenerHLR(ByVal asyncResult As System.IAsyncResult, ByRef idTransaccion As String, ByRef mensajeResultado As String, ByRef codigoHlr As String, ByRef itReturn() As itReturnType) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            idTransaccion = CType(results(1),String)
            mensajeResultado = CType(results(2),String)
            codigoHlr = CType(results(3),String)
            itReturn = CType(results(4),itReturnType())
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class itDataType
        
        '<remarks/>
        Public nroTelef As String
        
        '<remarks/>
        Public codigoHlr As String
        
        '<remarks/>
        Public descClred As String
        
        '<remarks/>
        Public descRegio As String
        
        '<remarks/>
        Public descTpcli As String
        
        '<remarks/>
        Public descTptlf As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class itTelSerType
        
        '<remarks/>
        Public nroTelef As String
        
        '<remarks/>
        Public nroSerie As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class itMatSerType
        
        '<remarks/>
        Public material As String
        
        '<remarks/>
        Public nroSerie As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class nroSimcardsDataType
        
        '<remarks/>
        Public nroTelef As String
        
        '<remarks/>
        Public [region] As String
        
        '<remarks/>
        Public codigoRed As String
        
        '<remarks/>
        Public codigoHlr As String
        
        '<remarks/>
        Public status As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public fecCarga As Date
        
        '<remarks/>
        Public usoCarga As String
        
        '<remarks/>
        Public tipoNro As String
        
        '<remarks/>
        Public loteBscs As String
        
        '<remarks/>
        Public tipoCliente As String
        
        '<remarks/>
        Public codigoDest As String
        
        '<remarks/>
        Public loteDest As String
        
        '<remarks/>
        Public loteMkt As String
        
        '<remarks/>
        Public serNr As String
        
        '<remarks/>
        Public matNr As String
        
        '<remarks/>
        Public kunNr As String
        
        '<remarks/>
        Public matNrAntig As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public fecTrafico As Date
        
        '<remarks/>
        Public bm As String
        
        '<remarks/>
        Public tipoDocCliente As String
        
        '<remarks/>
        Public cliente As String
        
        '<remarks/>
        Public statusChipRep As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public fecCambio As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class itNroTelType
        
        '<remarks/>
        Public nroTelef As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class itWorkType
        
        '<remarks/>
        Public nroTelef As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class etDetalleType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public correl As String
        
        '<remarks/>
        Public rangoInicial As String
        
        '<remarks/>
        Public rangoFinal As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public cantidad As String
        
        '<remarks/>
        Public [region] As String
        
        '<remarks/>
        Public inC As String
        
        '<remarks/>
        Public codigoHlr As String
        
        '<remarks/>
        Public regionDes As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class esResumenType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public cantSol As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public cantCarg As String
        
        '<remarks/>
        Public codigoHlr As String
        
        '<remarks/>
        Public [region] As String
        
        '<remarks/>
        Public regionDes As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class gtOutTabType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public codRet As String
        
        '<remarks/>
        Public desCod As String
        
        '<remarks/>
        Public texto As String
        
        '<remarks/>
        Public statusSim As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class itNumTelefType
        
        '<remarks/>
        Public nroTelef As String
        
        '<remarks/>
        Public marcCorta As String
        
        '<remarks/>
        Public codigRtpe As String
        
        '<remarks/>
        Public pniAbierto As String
        
        '<remarks/>
        Public empresa As String
        
        '<remarks/>
        Public bezei As String
        
        '<remarks/>
        Public descrRed As String
        
        '<remarks/>
        Public codigoHlr As String
        
        '<remarks/>
        Public descrStatus As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/sap/simcards/types")>  _
    Public Class itReturnType
        
        '<remarks/>
        Public tipo As String
        
        '<remarks/>
        Public claseMensaje As String
        
        '<remarks/>
        Public numeroMensaje As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public numeroLog As String
        
        '<remarks/>
        Public numeroConsecutivoInterno As String
        
        '<remarks/>
        Public mensajeV1 As String
        
        '<remarks/>
        Public mensajeV2 As String
        
        '<remarks/>
        Public mensajeV3 As String
        
        '<remarks/>
        Public mensajeV4 As String
        
        '<remarks/>
        Public parametro As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public lineas As String
        
        '<remarks/>
        Public campo As String
        
        '<remarks/>
        Public sistema As String
        
        '<remarks/>
        Public codigo As String
    End Class
End Namespace
