
<%	StrHtml = StrHtml & "<table width='380' border=0 ><tr><td>"
	StrHtml = StrHtml & "<tr>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>Nro. Recarga</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>" & numrecarga & "</font></td>" 
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr >"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>Recarga Efectiva</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>" & recargaefectiva & "</font></td>" 
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr >"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>Valor de Venta</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>" & valorventa & "</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr >"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>Descuento</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>" & descuento & "</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr >"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>SubTotal</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>" & valorventa - descuento & "</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr >"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>I.G.V.(" & CDbl(ConfigurationSettings.AppSettings("constIGV"))*100 & "%" & ")</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>" & igv & "</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>Ajuste Redondeo</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>0.00</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;&nbsp;&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>Total</font></td>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>" & totalpago & "</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "</table>"
	StrHtml = StrHtml & "<Table border='0' bordercolor='#000000' width='600'>"
	StrHtml = StrHtml & "<tr>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='left'><FONT  face='Arial' size=1>Vigencia: S/10 a S/19 (15 dias), S/20 (65 días), S/21 a S/30 (85 días), S/31 a S/40 (95 días).</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='left'><FONT  face='Arial' size=1>S/41 a S/50 (105 días) y más de S/50 (120 días)</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "<tr>"
	StrHtml = StrHtml & "<td align='right'><FONT  face='Arial' size=1>&nbsp;</font></td>"
	StrHtml = StrHtml & "<td align='left'><FONT  face='Arial' size=1>Para Postpago Control: S/10 a S/19 (45 dias)</font></td>"
	StrHtml = StrHtml & "</tr>"
	StrHtml = StrHtml & "</td></tr></table>"
	%>