'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace EnviarCorreoWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="envioCorreoWSPortSB11Binding", [Namespace]:="http://claro.com.pe/eai/util/enviocorreo")>  _
    Public Class envioCorreoWSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv28.tim.com.pe:8909/EnvioCorreoWS/envioCorreoWSPortSB11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/util/enviocorreo/enviarCorreo", RequestElementName:="enviarCorreoRequest", RequestNamespace:="http://claro.com.pe/eai/util/enviocorreo", ResponseNamespace:="http://claro.com.pe/eai/util/enviocorreo", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function enviarCorreo(ByVal auditRequest As AuditTypeRequest, ByVal remitente As String, ByVal destinatario As String, ByVal asunto As String, ByVal mensaje As String, ByVal htmlFlag As String, <System.Xml.Serialization.XmlArrayItemAttribute("ParametroComplexType", IsNullable:=false)> ByVal parametrosOpcionalesRequest() As ParametroOpcionalComplexType, <System.Xml.Serialization.XmlArrayItemAttribute("ParametroComplexType", IsNullable:=false)> ByRef parametrosOpcionalesResponse() As ParametroOpcionalComplexType) As <System.Xml.Serialization.XmlElementAttribute("auditResponse")> AuditTypeResponse
            Dim results() As Object = Me.Invoke("enviarCorreo", New Object() {auditRequest, remitente, destinatario, asunto, mensaje, htmlFlag, parametrosOpcionalesRequest})
            parametrosOpcionalesResponse = CType(results(1),ParametroOpcionalComplexType())
            Return CType(results(0),AuditTypeResponse)
        End Function
        
        '<remarks/>
        Public Function BeginenviarCorreo(ByVal auditRequest As AuditTypeRequest, ByVal remitente As String, ByVal destinatario As String, ByVal asunto As String, ByVal mensaje As String, ByVal htmlFlag As String, ByVal parametrosOpcionalesRequest() As ParametroOpcionalComplexType, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("enviarCorreo", New Object() {auditRequest, remitente, destinatario, asunto, mensaje, htmlFlag, parametrosOpcionalesRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndenviarCorreo(ByVal asyncResult As System.IAsyncResult, ByRef parametrosOpcionalesResponse() As ParametroOpcionalComplexType) As AuditTypeResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            parametrosOpcionalesResponse = CType(results(1),ParametroOpcionalComplexType())
            Return CType(results(0),AuditTypeResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/util/enviocorreo")>  _
    Public Class AuditTypeRequest
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoAplicacion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public usrAplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/util/enviocorreo")>  _
    Public Class AuditTypeResponse
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoRespuesta As String
        
        '<remarks/>
        Public mensajeRespuesta As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/util/enviocorreo")>  _
    Public Class ParametroOpcionalComplexType
        
        '<remarks/>
        Public clave As String
        
        '<remarks/>
        Public valor As String
    End Class
End Namespace
