
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 21/05/2008
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Recaudacion
{

  [RfcStructure(AbapName ="ZST_RFC_COMP_M" , Length = 104)]
  public class ZST_RFC_COMP_M : SAPStructure
  {
    
    [RfcField(AbapName = "NUMERO_OPERACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Offset = 0)]
    [XmlElement("NUMERO_OPERACION")]
    public string Numero_Operacion
    { 
       get
       {
          return _Numero_Operacion;
       }
       set
       {
          _Numero_Operacion = value;
       }
    }
    private string _Numero_Operacion;

    [RfcField(AbapName = "CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 12)]
    [XmlElement("CLIENTE")]
    public string Cliente
    { 
       get
       {
          return _Cliente;
       }
       set
       {
          _Cliente = value;
       }
    }
    private string _Cliente;

    [RfcField(AbapName = "FECHA", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 22)]
    [XmlElement("FECHA")]
    public string Fecha
    { 
       get
       {
          return _Fecha;
       }
       set
       {
          _Fecha = value;
       }
    }
    private string _Fecha;

    [RfcField(AbapName = "MONTO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 30)]
    [XmlElement("MONTO")]
    public Decimal Monto
    { 
       get
       {
          return _Monto;
       }
       set
       {
          _Monto = value;
       }
    }
    private Decimal _Monto;

    [RfcField(AbapName = "VIA_PAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 38)]
    [XmlElement("VIA_PAGO")]
    public string Via_Pago
    { 
       get
       {
          return _Via_Pago;
       }
       set
       {
          _Via_Pago = value;
       }
    }
    private string _Via_Pago;

    [RfcField(AbapName = "NAME1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 42)]
    [XmlElement("NAME1")]
    public string Name1
    { 
       get
       {
          return _Name1;
       }
       set
       {
          _Name1 = value;
       }
    }
    private string _Name1;

    [RfcField(AbapName = "STCD1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 62)]
    [XmlElement("STCD1")]
    public string Stcd1
    { 
       get
       {
          return _Stcd1;
       }
       set
       {
          _Stcd1 = value;
       }
    }
    private string _Stcd1;

    [RfcField(AbapName = "DOCUMENTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Offset = 77)]
    [XmlElement("DOCUMENTO")]
    public string Documento
    { 
       get
       {
          return _Documento;
       }
       set
       {
          _Documento = value;
       }
    }
    private string _Documento;

    [RfcField(AbapName = "BANCO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 89)]
    [XmlElement("BANCO")]
    public string Banco
    { 
       get
       {
          return _Banco;
       }
       set
       {
          _Banco = value;
       }
    }
    private string _Banco;

  }

}
