
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 21/05/2008
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Recaudacion
{

  [RfcStructure(AbapName ="ZST_DEUDA_RECAUDACION" , Length = 193)]
  public class ZST_DEUDA_RECAUDACION : SAPStructure
  {
    
    [RfcField(AbapName = "NRO_TRANSACCION", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 0)]
    [XmlElement("NRO_TRANSACCION")]
    public string Nro_Transaccion
    { 
       get
       {
          return _Nro_Transaccion;
       }
       set
       {
          _Nro_Transaccion = value;
       }
    }
    private string _Nro_Transaccion;

    [RfcField(AbapName = "NOM_DEUDOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 10)]
    [XmlElement("NOM_DEUDOR")]
    public string Nom_Deudor
    { 
       get
       {
          return _Nom_Deudor;
       }
       set
       {
          _Nom_Deudor = value;
       }
    }
    private string _Nom_Deudor;

    [RfcField(AbapName = "RUC_DEUDOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 30)]
    [XmlElement("RUC_DEUDOR")]
    public string Ruc_Deudor
    { 
       get
       {
          return _Ruc_Deudor;
       }
       set
       {
          _Ruc_Deudor = value;
       }
    }
    private string _Ruc_Deudor;

    [RfcField(AbapName = "OFICINA_VENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 45)]
    [XmlElement("OFICINA_VENTA")]
    public string Oficina_Venta
    { 
       get
       {
          return _Oficina_Venta;
       }
       set
       {
          _Oficina_Venta = value;
       }
    }
    private string _Oficina_Venta;

    [RfcField(AbapName = "NOM_OF_VENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 49)]
    [XmlElement("NOM_OF_VENTA")]
    public string Nom_Of_Venta
    { 
       get
       {
          return _Nom_Of_Venta;
       }
       set
       {
          _Nom_Of_Venta = value;
       }
    }
    private string _Nom_Of_Venta;

    [RfcField(AbapName = "MON_PAGO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Offset = 69)]
    [XmlElement("MON_PAGO")]
    public string Mon_Pago
    { 
       get
       {
          return _Mon_Pago;
       }
       set
       {
          _Mon_Pago = value;
       }
    }
    private string _Mon_Pago;

    [RfcField(AbapName = "IMPORTE_PAGO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 72)]
    [XmlElement("IMPORTE_PAGO")]
    public Decimal Importe_Pago
    { 
       get
       {
          return _Importe_Pago;
       }
       set
       {
          _Importe_Pago = value;
       }
    }
    private Decimal _Importe_Pago;

    [RfcField(AbapName = "FECHA_TRANSAC", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 80)]
    [XmlElement("FECHA_TRANSAC")]
    public string Fecha_Transac
    { 
       get
       {
          return _Fecha_Transac;
       }
       set
       {
          _Fecha_Transac = value;
       }
    }
    private string _Fecha_Transac;

    [RfcField(AbapName = "HORA_TRANSAC", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 88)]
    [XmlElement("HORA_TRANSAC")]
    public string Hora_Transac
    { 
       get
       {
          return _Hora_Transac;
       }
       set
       {
          _Hora_Transac = value;
       }
    }
    private string _Hora_Transac;

    [RfcField(AbapName = "ESTADO_TRANSAC", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Offset = 94)]
    [XmlElement("ESTADO_TRANSAC")]
    public string Estado_Transac
    { 
       get
       {
          return _Estado_Transac;
       }
       set
       {
          _Estado_Transac = value;
       }
    }
    private string _Estado_Transac;

    [RfcField(AbapName = "NRO_TELEFONO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 95)]
    [XmlElement("NRO_TELEFONO")]
    public string Nro_Telefono
    { 
       get
       {
          return _Nro_Telefono;
       }
       set
       {
          _Nro_Telefono = value;
       }
    }
    private string _Nro_Telefono;

    [RfcField(AbapName = "COD_CAJERO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 110)]
    [XmlElement("COD_CAJERO")]
    public string Cod_Cajero
    { 
       get
       {
          return _Cod_Cajero;
       }
       set
       {
          _Cod_Cajero = value;
       }
    }
    private string _Cod_Cajero;

    [RfcField(AbapName = "NOM_CAJERO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 120)]
    [XmlElement("NOM_CAJERO")]
    public string Nom_Cajero
    { 
       get
       {
          return _Nom_Cajero;
       }
       set
       {
          _Nom_Cajero = value;
       }
    }
    private string _Nom_Cajero;

    [RfcField(AbapName = "NRO_TRACE_CONS", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 160)]
    [XmlElement("NRO_TRACE_CONS")]
    public string Nro_Trace_Cons
    { 
       get
       {
          return _Nro_Trace_Cons;
       }
       set
       {
          _Nro_Trace_Cons = value;
       }
    }
    private string _Nro_Trace_Cons;

    [RfcField(AbapName = "TIPO_DOC_DEUDOR", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 170)]
    [XmlElement("TIPO_DOC_DEUDOR")]
    public string Tipo_Doc_Deudor
    { 
       get
       {
          return _Tipo_Doc_Deudor;
       }
       set
       {
          _Tipo_Doc_Deudor = value;
       }
    }
    private string _Tipo_Doc_Deudor;

    [RfcField(AbapName = "NRO_DOC_DEUDOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 21, Offset = 172)]
    [XmlElement("NRO_DOC_DEUDOR")]
    public string Nro_Doc_Deudor
    { 
       get
       {
          return _Nro_Doc_Deudor;
       }
       set
       {
          _Nro_Doc_Deudor = value;
       }
    }
    private string _Nro_Doc_Deudor;

  }

}
