
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 21/05/2008
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Recaudacion
{

  [RfcStructure(AbapName ="ZST_RECIBO_RECAUDACION" , Length = 142)]
  public class ZST_RECIBO_RECAUDACION : SAPStructure
  {
    
    [RfcField(AbapName = "NRO_TRANSACCION", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 0)]
    [XmlElement("NRO_TRANSACCION")]
    public string Nro_Transaccion
    { 
       get
       {
          return _Nro_Transaccion;
       }
       set
       {
          _Nro_Transaccion = value;
       }
    }
    private string _Nro_Transaccion;

    [RfcField(AbapName = "POSICION", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Offset = 10)]
    [XmlElement("POSICION")]
    public string Posicion
    { 
       get
       {
          return _Posicion;
       }
       set
       {
          _Posicion = value;
       }
    }
    private string _Posicion;

    [RfcField(AbapName = "TIPO_DOC_RECAUD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 16)]
    [XmlElement("TIPO_DOC_RECAUD")]
    public string Tipo_Doc_Recaud
    { 
       get
       {
          return _Tipo_Doc_Recaud;
       }
       set
       {
          _Tipo_Doc_Recaud = value;
       }
    }
    private string _Tipo_Doc_Recaud;

    [RfcField(AbapName = "NRO_DOC_RECAUD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 19)]
    [XmlElement("NRO_DOC_RECAUD")]
    public string Nro_Doc_Recaud
    { 
       get
       {
          return _Nro_Doc_Recaud;
       }
       set
       {
          _Nro_Doc_Recaud = value;
       }
    }
    private string _Nro_Doc_Recaud;

    [RfcField(AbapName = "MONEDA_DOCUM", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Offset = 35)]
    [XmlElement("MONEDA_DOCUM")]
    public string Moneda_Docum
    { 
       get
       {
          return _Moneda_Docum;
       }
       set
       {
          _Moneda_Docum = value;
       }
    }
    private string _Moneda_Docum;

    [RfcField(AbapName = "IMPORTE_RECIBO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 38)]
    [XmlElement("IMPORTE_RECIBO")]
    public Decimal Importe_Recibo
    { 
       get
       {
          return _Importe_Recibo;
       }
       set
       {
          _Importe_Recibo = value;
       }
    }
    private Decimal _Importe_Recibo;

    [RfcField(AbapName = "IMPORTE_PAGADO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 46)]
    [XmlElement("IMPORTE_PAGADO")]
    public Decimal Importe_Pagado
    { 
       get
       {
          return _Importe_Pagado;
       }
       set
       {
          _Importe_Pagado = value;
       }
    }
    private Decimal _Importe_Pagado;

    [RfcField(AbapName = "NRO_COBRANZA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Offset = 54)]
    [XmlElement("NRO_COBRANZA")]
    public string Nro_Cobranza
    { 
       get
       {
          return _Nro_Cobranza;
       }
       set
       {
          _Nro_Cobranza = value;
       }
    }
    private string _Nro_Cobranza;

    [RfcField(AbapName = "NRO_OPE_ACREE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Offset = 66)]
    [XmlElement("NRO_OPE_ACREE")]
    public string Nro_Ope_Acree
    { 
       get
       {
          return _Nro_Ope_Acree;
       }
       set
       {
          _Nro_Ope_Acree = value;
       }
    }
    private string _Nro_Ope_Acree;

    [RfcField(AbapName = "FECHA_EMISION", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 78)]
    [XmlElement("FECHA_EMISION")]
    public string Fecha_Emision
    { 
       get
       {
          return _Fecha_Emision;
       }
       set
       {
          _Fecha_Emision = value;
       }
    }
    private string _Fecha_Emision;

    [RfcField(AbapName = "FECHA_PAGO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 86)]
    [XmlElement("FECHA_PAGO")]
    public string Fecha_Pago
    { 
       get
       {
          return _Fecha_Pago;
       }
       set
       {
          _Fecha_Pago = value;
       }
    }
    private string _Fecha_Pago;

    [RfcField(AbapName = "NRO_TRACE_ANUL", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 94)]
    [XmlElement("NRO_TRACE_ANUL")]
    public string Nro_Trace_Anul
    { 
       get
       {
          return _Nro_Trace_Anul;
       }
       set
       {
          _Nro_Trace_Anul = value;
       }
    }
    private string _Nro_Trace_Anul;

    [RfcField(AbapName = "NRO_TRACE_PAGO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 104)]
    [XmlElement("NRO_TRACE_PAGO")]
    public string Nro_Trace_Pago
    { 
       get
       {
          return _Nro_Trace_Pago;
       }
       set
       {
          _Nro_Trace_Pago = value;
       }
    }
    private string _Nro_Trace_Pago;

    [RfcField(AbapName = "DESC_SERVICIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 114)]
    [XmlElement("DESC_SERVICIO")]
    public string Desc_Servicio
    { 
       get
       {
          return _Desc_Servicio;
       }
       set
       {
          _Desc_Servicio = value;
       }
    }
    private string _Desc_Servicio;

    [RfcField(AbapName = "FECHA_HORA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 129)]
    [XmlElement("FECHA_HORA")]
    public string Fecha_Hora
    { 
       get
       {
          return _Fecha_Hora;
       }
       set
       {
          _Fecha_Hora = value;
       }
    }
    private string _Fecha_Hora;

    [RfcField(AbapName = "SERVICIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 139)]
    [XmlElement("SERVICIO")]
    public string Servicio
    { 
       get
       {
          return _Servicio;
       }
       set
       {
          _Servicio = value;
       }
    }
    private string _Servicio;

  }

}
