
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 21/05/2008
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Recaudacion
{

  public class ZST_RFC_TELF_DEUTable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZST_RFC_TELF_DEU));
    }
 
    public override object CreateNewRow()
    { 
        return new ZST_RFC_TELF_DEU();
    }
     
    public ZST_RFC_TELF_DEU this[int index] 
    {
        get 
        {
            return ((ZST_RFC_TELF_DEU)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZST_RFC_TELF_DEU value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZST_RFC_TELF_DEU value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZST_RFC_TELF_DEU value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZST_RFC_TELF_DEU value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZST_RFC_TELF_DEU value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZST_RFC_TELF_DEU[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
