'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace AjustePedidoAsurionWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AjustePedidoAsurionWSPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ws/ventas/ajustepedidoasurionws")>  _
    Public Class AjustePedidoAsurionWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv19.tim.com.pe:8909/AjustePedidoAsurionWS/ebsAjustePedidoAsurionS"& _ 
"B11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/ventas/ajustepedidoasurionws/ajustarPedido", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ajustarPedido(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/ventas/ajustepedidoasurionws/types")> ByVal ajustarPedidoRequest As ajustarPedidoRequest) As <System.Xml.Serialization.XmlElementAttribute("ajustarPedidoResponse", [Namespace]:="http://claro.com.pe/eai/ws/ventas/ajustepedidoasurionws/types")> ajustarPedidoResponse
            Dim results() As Object = Me.Invoke("ajustarPedido", New Object() {ajustarPedidoRequest})
            Return CType(results(0),ajustarPedidoResponse)
        End Function
        
        '<remarks/>
        Public Function BeginajustarPedido(ByVal ajustarPedidoRequest As ajustarPedidoRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ajustarPedido", New Object() {ajustarPedidoRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndajustarPedido(ByVal asyncResult As System.IAsyncResult) As ajustarPedidoResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ajustarPedidoResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/ventas/ajustepedidoasurionws/types")>  _
    Public Class ajustarPedidoRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public numPedido As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class auditRequestType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public nombreAplicacion As String
        
        '<remarks/>
        Public usuarioAplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class auditResponseType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoRespuesta As String
        
        '<remarks/>
        Public mensajeRespuesta As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/ventas/ajustepedidoasurionws/types")>  _
    Public Class ajustarPedidoResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class parametrosTypeObjetoOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public campo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
End Namespace
