'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
'
Namespace CanjeDescuentoEquipoWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ebsCanjeDevolucionServicioComercialPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class ebsCanjeDevolucionServicioComercialService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv13.tim.com.pe:7909/CanjeDevolucionServicioComercial/ebsCanjeDevo"& _ 
"lucionServicioComercial"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial/canjeSe"& _ 
"rvicioComercial", RequestElementName:="canjeServicioComercialRequest", RequestNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial", ResponseNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function canjeServicioComercial(ByVal infoDeTransaccion As InfoDeTransaccionType, ByVal datosClienteyPuntoDeVenta As DatosClienteyPuntoDeVentaType, <System.Xml.Serialization.XmlArrayItemAttribute("datosDeProductoCanje", IsNullable:=false)> ByVal listaDeProductosCanje() As DatosDeProductoCanjeType, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String) As <System.Xml.Serialization.XmlElementAttribute("idTransaccion")> String
            Dim results() As Object = Me.Invoke("canjeServicioComercial", New Object() {infoDeTransaccion, datosClienteyPuntoDeVenta, listaDeProductosCanje})
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegincanjeServicioComercial(ByVal infoDeTransaccion As InfoDeTransaccionType, ByVal datosClienteyPuntoDeVenta As DatosClienteyPuntoDeVentaType, ByVal listaDeProductosCanje() As DatosDeProductoCanjeType, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("canjeServicioComercial", New Object() {infoDeTransaccion, datosClienteyPuntoDeVenta, listaDeProductosCanje}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcanjeServicioComercial(ByVal asyncResult As System.IAsyncResult, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial/devoluc"& _ 
"ionServicioComercial", RequestElementName:="devolucionServicioComercialRequest", RequestNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial", ResponseNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function devolucionServicioComercial(ByVal infoDeTransaccion As InfoDeTransaccionType, ByVal datosClienteyPuntoDeVenta As DatosClienteyPuntoDeVentaType, <System.Xml.Serialization.XmlArrayItemAttribute("datosDeProductoDevolucion", IsNullable:=false)> ByVal listaDeProductosDevolucion() As DatosDeProductoDevolucionType, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String) As <System.Xml.Serialization.XmlElementAttribute("idTransaccion")> String
            Dim results() As Object = Me.Invoke("devolucionServicioComercial", New Object() {infoDeTransaccion, datosClienteyPuntoDeVenta, listaDeProductosDevolucion})
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegindevolucionServicioComercial(ByVal infoDeTransaccion As InfoDeTransaccionType, ByVal datosClienteyPuntoDeVenta As DatosClienteyPuntoDeVentaType, ByVal listaDeProductosDevolucion() As DatosDeProductoDevolucionType, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("devolucionServicioComercial", New Object() {infoDeTransaccion, datosClienteyPuntoDeVenta, listaDeProductosDevolucion}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EnddevolucionServicioComercial(ByVal asyncResult As System.IAsyncResult, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial/canjeSe"& _ 
"rvicioComercialFija", RequestElementName:="canjeServicioComercialFijaRequest", RequestNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial", ResponseNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function canjeServicioComercialFija(ByVal infoDeTransaccion As InfoDeTransaccionType, ByVal datosClienteyPuntoDeVenta As DatosClienteFijaType, <System.Xml.Serialization.XmlArrayItemAttribute("datosProductoCanjeFija", IsNullable:=false)> ByVal listaDeProductosCanje() As DatosDeProductoCanjeFijaType, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String, ByRef idCanjeClaroClub As String, ByRef idInteraccionClarify As String) As <System.Xml.Serialization.XmlElementAttribute("idTransaccion")> String
            Dim results() As Object = Me.Invoke("canjeServicioComercialFija", New Object() {infoDeTransaccion, datosClienteyPuntoDeVenta, listaDeProductosCanje})
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            idCanjeClaroClub = CType(results(3),String)
            idInteraccionClarify = CType(results(4),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegincanjeServicioComercialFija(ByVal infoDeTransaccion As InfoDeTransaccionType, ByVal datosClienteyPuntoDeVenta As DatosClienteFijaType, ByVal listaDeProductosCanje() As DatosDeProductoCanjeFijaType, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("canjeServicioComercialFija", New Object() {infoDeTransaccion, datosClienteyPuntoDeVenta, listaDeProductosCanje}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcanjeServicioComercialFija(ByVal asyncResult As System.IAsyncResult, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String, ByRef idCanjeClaroClub As String, ByRef idInteraccionClarify As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            idCanjeClaroClub = CType(results(3),String)
            idInteraccionClarify = CType(results(4),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial/canjeDe"& _ 
"scuentoEquipo", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function canjeDescuentoEquipo(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")> ByVal canjeDescuentoEquipoRequest As canjeDescuentoEquipoRequest) As <System.Xml.Serialization.XmlElementAttribute("canjeDescuentoEquipoResponse", [Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")> canjeDescuentoEquipoResponse
            Dim results() As Object = Me.Invoke("canjeDescuentoEquipo", New Object() {canjeDescuentoEquipoRequest})
            Return CType(results(0),canjeDescuentoEquipoResponse)
        End Function
        
        '<remarks/>
        Public Function BegincanjeDescuentoEquipo(ByVal canjeDescuentoEquipoRequest As canjeDescuentoEquipoRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("canjeDescuentoEquipo", New Object() {canjeDescuentoEquipoRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcanjeDescuentoEquipo(ByVal asyncResult As System.IAsyncResult) As canjeDescuentoEquipoResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),canjeDescuentoEquipoResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial/devoluc"& _ 
"ionDescuentoEquipo", RequestElementName:="devolucionDescuentoEquipoRequest", RequestNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial", ResponseNamespace:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function devolucionDescuentoEquipo(ByVal infoDeTransaccion As InfoDeTransaccionType, ByVal idSolicitud As String, ByVal puntoVenta As String, ByVal idVenta As String, ByVal proceso As String, ByVal linea As String, ByVal tipoDoc As String, ByVal numDoc As String, ByVal ptosDevueltos As String, ByVal solesDevueltos As String, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String, ByRef saldo As String) As <System.Xml.Serialization.XmlElementAttribute("idTransaccion")> String
            Dim results() As Object = Me.Invoke("devolucionDescuentoEquipo", New Object() {infoDeTransaccion, idSolicitud, puntoVenta, idVenta, proceso, linea, tipoDoc, numDoc, ptosDevueltos, solesDevueltos})
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            saldo = CType(results(3),String)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegindevolucionDescuentoEquipo(ByVal infoDeTransaccion As InfoDeTransaccionType, ByVal idSolicitud As String, ByVal puntoVenta As String, ByVal idVenta As String, ByVal proceso As String, ByVal linea As String, ByVal tipoDoc As String, ByVal numDoc As String, ByVal ptosDevueltos As String, ByVal solesDevueltos As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("devolucionDescuentoEquipo", New Object() {infoDeTransaccion, idSolicitud, puntoVenta, idVenta, proceso, linea, tipoDoc, numDoc, ptosDevueltos, solesDevueltos}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EnddevolucionDescuentoEquipo(ByVal asyncResult As System.IAsyncResult, ByRef codigoRespuesta As String, ByRef mensajeRespuesta As String, ByRef saldo As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            codigoRespuesta = CType(results(1),String)
            mensajeRespuesta = CType(results(2),String)
            saldo = CType(results(3),String)
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class InfoDeTransaccionType
        
        '<remarks/>
        Public usrApp As String
        
        '<remarks/>
        Public usrName As String
        
        '<remarks/>
        Public aplicacion As String
        
        '<remarks/>
        Public estacion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public fechaHora As String
        
        '<remarks/>
        Public idTransaccion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class DatosCanjeType
        
        '<remarks/>
        Public proId As String
        
        '<remarks/>
        Public proDes As String
        
        '<remarks/>
        Public campana As String
        
        '<remarks/>
        Public puntos As Integer
        
        '<remarks/>
        Public pago As Integer
        
        '<remarks/>
        Public cantidad As Integer
        
        '<remarks/>
        Public idCanje As Integer
        
        '<remarks/>
        Public idCanjeSec As Integer
        
        '<remarks/>
        Public tipoPremio As String
        
        '<remarks/>
        Public servComercial As Integer
        
        '<remarks/>
        Public montoRecarga As Integer
        
        '<remarks/>
        Public codTipoCliente As String
        
        '<remarks/>
        Public telefono As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class canjeDescuentoEquipoResponse
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoRespuesta As String
        
        '<remarks/>
        Public mensajeRespuesta As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("datosCanje", IsNullable:=false)>  _
        Public listaCanje() As DatosCanjeType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class canjeDescuentoEquipoRequest
        
        '<remarks/>
        Public infoDeTransaccion As InfoDeTransaccionType
        
        '<remarks/>
        Public nombreCliente As String
        
        '<remarks/>
        Public tipoDocumento As String
        
        '<remarks/>
        Public numDocumento As String
        
        '<remarks/>
        Public puntoVenta As String
        
        '<remarks/>
        Public codAplicacion As String
        
        '<remarks/>
        Public codAsesor As String
        
        '<remarks/>
        Public nomAsesor As String
        
        '<remarks/>
        Public idVenta As String
        
        '<remarks/>
        Public idProceso As String
        
        '<remarks/>
        Public puntosVenta As Integer
        
        '<remarks/>
        Public solesVenta As Integer
        
        '<remarks/>
        Public idCampana As String
        
        '<remarks/>
        Public usuario As String
        
        '<remarks/>
        Public codigoCliente As String
        
        '<remarks/>
        Public segmento As String
        
        '<remarks/>
        Public lineaTipificacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class DatosDeProductoCanjeFijaType
        
        '<remarks/>
        Public proId As String
        
        '<remarks/>
        Public proDes As String
        
        '<remarks/>
        Public campana As String
        
        '<remarks/>
        Public puntos As String
        
        '<remarks/>
        Public pago As String
        
        '<remarks/>
        Public cantidad As String
        
        '<remarks/>
        Public coSer As String
        
        '<remarks/>
        Public montoRecarga As String
        
        '<remarks/>
        Public tipoProducto As String
        
        '<remarks/>
        Public codPaqDat As String
        
        '<remarks/>
        Public codPaqueteFija As String
        
        '<remarks/>
        Public nroDias As Integer
        
        '<remarks/>
        Public valSegmento As String
        
        '<remarks/>
        Public ptosDscto As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class DatosClienteFijaType
        
        '<remarks/>
        Public msisdn As String
        
        '<remarks/>
        Public tipoLinea As String
        
        '<remarks/>
        Public tipoCliente As String
        
        '<remarks/>
        Public nombreCliente As String
        
        '<remarks/>
        Public customerId As String
        
        '<remarks/>
        Public tipoDocumento As String
        
        '<remarks/>
        Public nroDocumento As String
        
        '<remarks/>
        Public coId As String
        
        '<remarks/>
        Public codigoCliente As String
        
        '<remarks/>
        Public puntoDeVenta As String
        
        '<remarks/>
        Public textoNotas As String
        
        '<remarks/>
        Public codClaroClubFija As String
        
        '<remarks/>
        Public codServicioFija As String
        
        '<remarks/>
        Public direccionServicioFija As String
        
        '<remarks/>
        Public palabraClaveSMS As String
        
        '<remarks/>
        Public codSegmento As String
        
        '<remarks/>
        Public usraSegmento As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class DatosDeProductoDevolucionType
        
        '<remarks/>
        Public proId As String
        
        '<remarks/>
        Public proDes As String
        
        '<remarks/>
        Public campana As String
        
        '<remarks/>
        Public puntos As String
        
        '<remarks/>
        Public pago As String
        
        '<remarks/>
        Public cantidad As String
        
        '<remarks/>
        Public coSer As String
        
        '<remarks/>
        Public montoExtorno As String
        
        '<remarks/>
        Public flagModificaSaldo As String
        
        '<remarks/>
        Public tipoProducto As String
        
        '<remarks/>
        Public idCanje As String
        
        '<remarks/>
        Public idCanjeSec As String
        
        '<remarks/>
        Public idCanjeLoyalti As String
        
        '<remarks/>
        Public codPaqDat As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class DatosDeProductoCanjeType
        
        '<remarks/>
        Public proId As String
        
        '<remarks/>
        Public proDes As String
        
        '<remarks/>
        Public campana As String
        
        '<remarks/>
        Public puntos As String
        
        '<remarks/>
        Public pago As String
        
        '<remarks/>
        Public cantidad As String
        
        '<remarks/>
        Public coSer As String
        
        '<remarks/>
        Public montoRecarga As String
        
        '<remarks/>
        Public flagModificaSaldo As String
        
        '<remarks/>
        Public tipoProducto As String
        
        '<remarks/>
        Public codPaqDat As String
        
        '<remarks/>
        Public valSegmento As String
        
        '<remarks/>
        Public ptosDscto As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ebs/ws/postventa/CanjeDevolucionServicioComercial")>  _
    Public Class DatosClienteyPuntoDeVentaType
        
        '<remarks/>
        Public msisdn As String
        
        '<remarks/>
        Public tipoCliente As String
        
        '<remarks/>
        Public nombreCliente As String
        
        '<remarks/>
        Public customerId As String
        
        '<remarks/>
        Public tipoDocumento As String
        
        '<remarks/>
        Public nroDocumento As String
        
        '<remarks/>
        Public coId As String
        
        '<remarks/>
        Public cacDac As String
        
        '<remarks/>
        Public idSolicitud As String
        
        '<remarks/>
        Public codigoCliente As String
        
        '<remarks/>
        Public puntoDeVenta As String
        
        '<remarks/>
        Public textoNotas As String
        
        '<remarks/>
        Public codSegmento As String
        
        '<remarks/>
        Public usraSegmento As String
        
        '<remarks/>
        Public codTipoCanje As String
        
        '<remarks/>
        Public codTPremioCanje As String
    End Class
End Namespace
