'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace WSActivacionPostPagoCBIO
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ActivacionPostpagoCBIOWSPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows")>  _
    Public Class ActivacionPostpagoCBIOWSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://127.0.0.1:7001/ActivacionPostpagoCBIOWS/ebsActivacionPostpagoCBIOSB11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/ejecutarActivacion", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ejecutarActivacion(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/types")> ByVal ejecutarActivacionRequest As ejecutarActivacionRequest) As <System.Xml.Serialization.XmlElementAttribute("ejecutarActivacionResponse", [Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/types")> ejecutarActivacionResponse
            Dim results() As Object = Me.Invoke("ejecutarActivacion", New Object() {ejecutarActivacionRequest})
            Return CType(results(0),ejecutarActivacionResponse)
        End Function
        
        '<remarks/>
        Public Function BeginejecutarActivacion(ByVal ejecutarActivacionRequest As ejecutarActivacionRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarActivacion", New Object() {ejecutarActivacionRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndejecutarActivacion(ByVal asyncResult As System.IAsyncResult) As ejecutarActivacionResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ejecutarActivacionResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/consultarRecursos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function consultarRecursos(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/types")> ByVal cosultarRecursosRequest As cosultarRecursosRequest) As <System.Xml.Serialization.XmlElementAttribute("cosultarRecursosResponse", [Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/types")> cosultarRecursosResponse
            Dim results() As Object = Me.Invoke("consultarRecursos", New Object() {cosultarRecursosRequest})
            Return CType(results(0),cosultarRecursosResponse)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarRecursos(ByVal cosultarRecursosRequest As cosultarRecursosRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarRecursos", New Object() {cosultarRecursosRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarRecursos(ByVal asyncResult As System.IAsyncResult) As cosultarRecursosResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),cosultarRecursosResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/types")>  _
    Public Class ejecutarActivacionRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        Public numeroAcuerdo As String
        
        '<remarks/>
        Public tipoProducto As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class auditRequestType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public ipAplicacion As String
        
        '<remarks/>
        Public nombreAplicacion As String
        
        '<remarks/>
        Public usuarioAplicacion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/types")>  _
    Public Class cosultarRecursosResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("recursos")>  _
        Public recursos() As recursoType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class auditResponseType
        
        '<remarks/>
        Public idTransaccion As String
        
        '<remarks/>
        Public codigoRespuesta As String
        
        '<remarks/>
        Public mensajeRespuesta As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class recursoType
        
        '<remarks/>
        Public linea As lineaType
        
        '<remarks/>
        Public imei As imeiType
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class lineaType
        
        '<remarks/>
        Public msisdn As String
        
        '<remarks/>
        Public status As String
        
        '<remarks/>
        Public sdpId As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class imeiType
        
        '<remarks/>
        Public iccid As String
        
        '<remarks/>
        Public status As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/baseschema")>  _
    Public Class parametrosTypeObjetoOpcional
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public campo As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public valor As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/types")>  _
    Public Class cosultarRecursosRequest
        
        '<remarks/>
        Public auditRequest As auditRequestType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("recursos")>  _
        Public recursos() As recursoType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaRequestOpcional() As parametrosTypeObjetoOpcional
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/eai/ws/post/activacionpostpagocbiows/types")>  _
    Public Class ejecutarActivacionResponse
        
        '<remarks/>
        Public auditResponse As auditResponseType
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", [Namespace]:="http://claro.com.pe/eai/ws/baseschema", IsNullable:=false)>  _
        Public listaResponseOpcional() As parametrosTypeObjetoOpcional
    End Class
End Namespace
