'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
'
Namespace ConsultaLineaCuentaWS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ConsultaLineaCuentaWSPortTypeSOAP11Binding", [Namespace]:="http://claro.com.pe/SOA/service/ConsultaLineaCuentaWS")>  _
    Public Class ConsultaLineaCuentaWSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost:20000/ConsultaLineaCuentaWS/ebsConsultaLineaCuentaWSSB11"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/SOA/service/ConsultaLineaCuentaWS/consultarLineaCuenta", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function consultarLineaCuenta(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://claro.com.pe/SOA/message/consultalineacuentaws")> ByVal consultarLineaCuentaRequest As consultarLineaCuentaRequest) As <System.Xml.Serialization.XmlElementAttribute("consultarLineaCuentaResponse", [Namespace]:="http://claro.com.pe/SOA/message/consultalineacuentaws")> consultarLineaCuentaResponse
            Dim results() As Object = Me.Invoke("consultarLineaCuenta", New Object() {consultarLineaCuentaRequest})
            Return CType(results(0),consultarLineaCuentaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginconsultarLineaCuenta(ByVal consultarLineaCuentaRequest As consultarLineaCuentaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("consultarLineaCuenta", New Object() {consultarLineaCuentaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndconsultarLineaCuenta(ByVal asyncResult As System.IAsyncResult) As consultarLineaCuentaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),consultarLineaCuentaResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/SOA/message/consultalineacuentaws")>  _
    Public Class consultarLineaCuentaRequest
        
        '<remarks/>
        Public tipoConsulta As String
        
        '<remarks/>
        Public valorConsulta As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://claro.com.pe/SOA/message/consultalineacuentaws")>  _
    Public Class consultarLineaCuentaResponse
        
        '<remarks/>
        Public rptaConsulta As String
    End Class
End Namespace
