
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27/01/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Ventas
{

  [RfcStructure(AbapName ="ZST_PV_UTILIZACION" , Length = 23)]
  public class ZST_PV_UTILIZACION : SAPStructure
  {
    
    [RfcField(AbapName = "ABRVW", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 0)]
    [XmlElement("ABRVW")]
    public string Abrvw
    { 
       get
       {
          return _Abrvw;
       }
       set
       {
          _Abrvw = value;
       }
    }
    private string _Abrvw;

    [RfcField(AbapName = "BEZEI", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 3)]
    [XmlElement("BEZEI")]
    public string Bezei
    { 
       get
       {
          return _Bezei;
       }
       set
       {
          _Bezei = value;
       }
    }
    private string _Bezei;

  }

}
