
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27/01/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Ventas
{

  [RfcStructure(AbapName ="ZST_PV_CAMPANA_ASOC" , Length = 210)]
  public class ZST_PV_CAMPANA_ASOC : SAPStructure
  {
    
    [RfcField(AbapName = "CAMPANA_PADRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 0)]
    [XmlElement("CAMPANA_PADRE")]
    public string Campana_Padre
    { 
       get
       {
          return _Campana_Padre;
       }
       set
       {
          _Campana_Padre = value;
       }
    }
    private string _Campana_Padre;

    [RfcField(AbapName = "CAMPANA_HIJO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 4)]
    [XmlElement("CAMPANA_HIJO")]
    public string Campana_Hijo
    { 
       get
       {
          return _Campana_Hijo;
       }
       set
       {
          _Campana_Hijo = value;
       }
    }
    private string _Campana_Hijo;

    [RfcField(AbapName = "NRO_TRIOS", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 8)]
    [XmlElement("NRO_TRIOS")]
    public string Nro_Trios
    { 
       get
       {
          return _Nro_Trios;
       }
       set
       {
          _Nro_Trios = value;
       }
    }
    private string _Nro_Trios;

    [RfcField(AbapName = "GLOSA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 200, Offset = 10)]
    [XmlElement("GLOSA")]
    public string Glosa
    { 
       get
       {
          return _Glosa;
       }
       set
       {
          _Glosa = value;
       }
    }
    private string _Glosa;

  }

}
