
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27/01/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Ventas
{

  [RfcStructure(AbapName ="ZST_PV_PROVINCIA" , Length = 45)]
  public class ZST_PV_PROVINCIA : SAPStructure
  {
    
    [RfcField(AbapName = "DEPARTAMENTO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 0)]
    [XmlElement("DEPARTAMENTO")]
    public string Departamento
    { 
       get
       {
          return _Departamento;
       }
       set
       {
          _Departamento = value;
       }
    }
    private string _Departamento;

    [RfcField(AbapName = "PROVINCIA", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Offset = 2)]
    [XmlElement("PROVINCIA")]
    public string Provincia
    { 
       get
       {
          return _Provincia;
       }
       set
       {
          _Provincia = value;
       }
    }
    private string _Provincia;

    [RfcField(AbapName = "DESCRIPCION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 5)]
    [XmlElement("DESCRIPCION")]
    public string Descripcion
    { 
       get
       {
          return _Descripcion;
       }
       set
       {
          _Descripcion = value;
       }
    }
    private string _Descripcion;

  }

}
