
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27/01/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Ventas
{

  [RfcStructure(AbapName ="ZST_PV_SERVI_CONTRA" , Length = 21)]
  public class ZST_PV_SERVI_CONTRA : SAPStructure
  {
    
    [RfcField(AbapName = "DOCUMENTO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 0)]
    [XmlElement("DOCUMENTO")]
    public string Documento
    { 
       get
       {
          return _Documento;
       }
       set
       {
          _Documento = value;
       }
    }
    private string _Documento;

    [RfcField(AbapName = "CONSECUTIVO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Offset = 10)]
    [XmlElement("CONSECUTIVO")]
    public string Consecutivo
    { 
       get
       {
          return _Consecutivo;
       }
       set
       {
          _Consecutivo = value;
       }
    }
    private string _Consecutivo;

    [RfcField(AbapName = "SERVICIO_SOLICIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 16)]
    [XmlElement("SERVICIO_SOLICIT")]
    public string Servicio_Solicit
    { 
       get
       {
          return _Servicio_Solicit;
       }
       set
       {
          _Servicio_Solicit = value;
       }
    }
    private string _Servicio_Solicit;

    [RfcField(AbapName = "VALOR_SELECCIONA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 20)]
    [XmlElement("VALOR_SELECCIONA")]
    public string Valor_Selecciona
    { 
       get
       {
          return _Valor_Selecciona;
       }
       set
       {
          _Valor_Selecciona = value;
       }
    }
    private string _Valor_Selecciona;

  }

}
