
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27/01/2010
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Ventas
{

  [RfcStructure(AbapName ="ZST_PV_GRUPO_ARTICULO" , Length = 9)]
  public class ZST_PV_GRUPO_ARTICULO : SAPStructure
  {
    
    [RfcField(AbapName = "MATKL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 9, Offset = 0)]
    [XmlElement("MATKL")]
    public string Matkl
    { 
       get
       {
          return _Matkl;
       }
       set
       {
          _Matkl = value;
       }
    }
    private string _Matkl;

  }

}
