
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 13/08/2013
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Ventas
{

  public class ZTI_CAB_PEDIDOTable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZTI_CAB_PEDIDO));
    }
 
    public override object CreateNewRow()
    { 
        return new ZTI_CAB_PEDIDO();
    }
     
    public ZTI_CAB_PEDIDO this[int index] 
    {
        get 
        {
            return ((ZTI_CAB_PEDIDO)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZTI_CAB_PEDIDO value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZTI_CAB_PEDIDO value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZTI_CAB_PEDIDO value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZTI_CAB_PEDIDO value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZTI_CAB_PEDIDO value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZTI_CAB_PEDIDO[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
