
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 13/08/2013
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAP_SIC_Ventas
{

  [RfcStructure(AbapName ="ZTI_DET_PEDIDO" , Length = 112)]
  public class ZTI_DET_PEDIDO : SAPStructure
  {
    
    [RfcField(AbapName = "POSNR", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Offset = 0)]
    [XmlElement("POSNR")]
    public string Posnr
    { 
       get
       {
          return _Posnr;
       }
       set
       {
          _Posnr = value;
       }
    }
    private string _Posnr;

    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Offset = 6)]
    [XmlElement("MATNR")]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;

    [RfcField(AbapName = "KWMENG", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 3, Offset = 24)]
    [XmlElement("KWMENG")]
    public Decimal Kwmeng
    { 
       get
       {
          return _Kwmeng;
       }
       set
       {
          _Kwmeng = value;
       }
    }
    private Decimal _Kwmeng;

    [RfcField(AbapName = "CAMPANA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 32)]
    [XmlElement("CAMPANA")]
    public string Campana
    { 
       get
       {
          return _Campana;
       }
       set
       {
          _Campana = value;
       }
    }
    private string _Campana;

    [RfcField(AbapName = "PLAN_TARIFARIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 36)]
    [XmlElement("PLAN_TARIFARIO")]
    public string Plan_Tarifario
    { 
       get
       {
          return _Plan_Tarifario;
       }
       set
       {
          _Plan_Tarifario = value;
       }
    }
    private string _Plan_Tarifario;

    [RfcField(AbapName = "ZZNRO_TELEF", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 39)]
    [XmlElement("ZZNRO_TELEF")]
    public string Zznro_Telef
    { 
       get
       {
          return _Zznro_Telef;
       }
       set
       {
          _Zznro_Telef = value;
       }
    }
    private string _Zznro_Telef;

    [RfcField(AbapName = "VKAUS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 54)]
    [XmlElement("VKAUS")]
    public string Vkaus
    { 
       get
       {
          return _Vkaus;
       }
       set
       {
          _Vkaus = value;
       }
    }
    private string _Vkaus;

    [RfcField(AbapName = "REC_EFECTIVA", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 57)]
    [XmlElement("REC_EFECTIVA")]
    public Decimal Rec_Efectiva
    { 
       get
       {
          return _Rec_Efectiva;
       }
       set
       {
          _Rec_Efectiva = value;
       }
    }
    private Decimal _Rec_Efectiva;

    [RfcField(AbapName = "VAL_VENTA", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 65)]
    [XmlElement("VAL_VENTA")]
    public Decimal Val_Venta
    { 
       get
       {
          return _Val_Venta;
       }
       set
       {
          _Val_Venta = value;
       }
    }
    private Decimal _Val_Venta;

    [RfcField(AbapName = "DESCUENTO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 73)]
    [XmlElement("DESCUENTO")]
    public Decimal Descuento
    { 
       get
       {
          return _Descuento;
       }
       set
       {
          _Descuento = value;
       }
    }
    private Decimal _Descuento;

    [RfcField(AbapName = "IGV", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 81)]
    [XmlElement("IGV")]
    public Decimal Igv
    { 
       get
       {
          return _Igv;
       }
       set
       {
          _Igv = value;
       }
    }
    private Decimal _Igv;

    [RfcField(AbapName = "TOTAL_PAGO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 89)]
    [XmlElement("TOTAL_PAGO")]
    public Decimal Total_Pago
    { 
       get
       {
          return _Total_Pago;
       }
       set
       {
          _Total_Pago = value;
       }
    }
    private Decimal _Total_Pago;

    [RfcField(AbapName = "NRO_REC_SWITCH", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 97)]
    [XmlElement("NRO_REC_SWITCH")]
    public string Nro_Rec_Switch
    { 
       get
       {
          return _Nro_Rec_Switch;
       }
       set
       {
          _Nro_Rec_Switch = value;
       }
    }
    private string _Nro_Rec_Switch;

  }

}
